project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - about.qmd
    - examples/

execute:
  freeze: auto

website:
  title: "EpiModel Gallery"
  description: "Template examples for extending EpiModel to model infectious disease dynamics over networks"
  navbar:
    background: dark
    left:
      - text: Gallery
        href: index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/EpiModel/EpiModel-Gallery
      - text: EpiModel
        href: https://www.epimodel.org/

  sidebar:
    style: docked
    search: true
    border: true
    collapse-level: 1
    contents:
      - section: Fundamentals
        contents:
          - examples/seir-exposed-state/index.qmd
          - examples/si-vital-dynamics/index.qmd
      - section: Interventions
        contents:
          - examples/seir-aon-vaccination/index.qmd
          - examples/seirs-leaky-vaccination/index.qmd
          - examples/sis-test-and-treat/index.qmd
      - section: Intermediate Extensions
        contents:
          - examples/sis-competing-strains/index.qmd
          - examples/social-diffusion/index.qmd
      - section: Full Disease Models
        contents:
          - examples/hiv/index.qmd
          - examples/syphilis/index.qmd
      - section: Network Features
        contents:
          - examples/observed-network-data/index.qmd
          - examples/multinets/index.qmd
      - section: Advanced Extensions
        contents:
          - examples/cost-effectiveness/index.qmd

format:
  html:
    theme: [cosmo, styles/_fonts.scss, styles/_theme.scss]
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1rem
    toc: true
    toc-location: left
    toc-expand: false
    code-copy: true
    code-overflow: wrap
    code-tools: true
