{
  "hash": "756096c30facf1fa6bbb282e4ebb7662",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Partner Notification for an Endemic Bacterial STI\"\ndescription: \"Partner notification for a chlamydia-like infection without immunity, in a heterosexual population of young adults with main and casual partnerships. A partner services module finds each diagnosed person's recent partners through EpiModel's cumulative edgelist and treats them by patient referral or expedited partner therapy. Every scenario resumes the same burn-in to endemic equilibrium, and the page reports prevalence, infections averted with Monte Carlo intervals, repeat infection of cured cases and its source, and whom partner services reaches.\"\nauthor: \"Samuel M. Jenness\"\ndate: \"2026-09-23\"\ncategories: [SIS, STI, partner notification, intervention, cumulative edgelist, burn-in and restart, intermediate]\norder: 6.5\nimage: thumbnail.png\n---\n\n## Overview\n\nPartner notification is the partner services intervention for sexually transmitted infections: when a person is diagnosed, the people they recently had sex with are told that they were exposed and are offered treatment. For a curable bacterial infection that leaves no immunity, such as chlamydia, it does two jobs. It finds infections in partners, most of which cause no symptoms and would otherwise go untested, and it protects the person who was just treated, because an untreated partner who is still infected will reinfect them ([Heijne et al. 2011](https://doi.org/10.1093/infdis/jiq050)). The second job has no counterpart in contact tracing for an immunizing infection, and it is why the [CDC treatment guidelines](https://doi.org/10.15585/mmwr.rr7004a1) make partner treatment part of the clinical management of the index case rather than only a public health activity.\n\nBoth jobs run through a sexual network. The partners who matter are the partners the index case actually had over a lookback window, some of them in partnerships that have already ended, and whether a partner can be reached depends on the kind of partnership it was. EpiModel keeps the record that makes this computable, the **cumulative edgelist**: every partnership the simulation has seen, in every network layer, with the steps on which it began and ended. This example uses it to model partner services for a chlamydia-like infection among heterosexual young adults, and to ask four questions from the trials and models of partner notification:\n\n1. **What does partner notification contribute?** The burn-in runs screening with patient referral (PR), in which the index case is asked to tell their partners, who then come in to be tested and treated. That is the usual standard of care in the United States, and the model is tuned to about 3% prevalence under it. Removing it shows what it contributes.\n2. **Patient referral or expedited partner therapy?** Under expedited partner therapy (EPT) the index case delivers medication to their partners. Trials found that it gets more partners treated and reduces repeat infection of the index case by about a quarter for chlamydia and gonorrhea combined, with smaller reductions for chlamydia alone that did not reach statistical significance ([Golden et al. 2005](https://doi.org/10.1056/NEJMoa041681); [Schillinger et al. 2003](https://doi.org/10.1097/00007435-200301000-00011); [Ferreira et al. 2013](https://doi.org/10.1002/14651858.CD002843.pub2)). It also gives something up: partners are never tested, so an infected partner is not diagnosed, and that partner's own partners are never notified. Patient referral keeps that chain.\n3. **How far back?** CDC guidance notifies partners from the 60 days before diagnosis; UK guidance uses six months for most cases ([McClean et al. 2013](https://doi.org/10.1177/0956462412472804)). A third option gives EPT to ongoing partners only, the partners to whom an index can most easily hand medication.\n4. **Where does the benefit go?** The model follows every case cured after diagnosis by screening or care-seeking for 13 weeks and, when one is reinfected, asks the cumulative edgelist when the transmitting partnership began. Reinfection by a partner the person already had when cured is the failure that partner notification is meant to prevent; reinfection by a new partner is not. Trials measure repeat infection and ask about new partners, but they cannot tell which partner transmitted.\n\n::: {.callout-note}\n## How this relates to the contact tracing example\n\nThe [contact tracing](../seir-contact-tracing/) example applies the same cumulative-edgelist functions to an acute respiratory infection. The two pages are meant to be read together, and each uses a part of the machinery that the other does not:\n\n| | Contact tracing | Partner notification |\n|---|---|---|\n| Infection | acute, immunizing (SEIR) | curable, no immunity (SIS) |\n| Time step and horizon | day; one epidemic | week; a 10-year burn-in, then 5 years of scenarios |\n| Starting point | seeded epidemic | endemic equilibrium from a burn-in that every scenario resumes |\n| Population | closed | open, with arrivals and departures, so unique and positional ids diverge |\n| Network | one layer of close contacts | main and casual partnership layers, heterosexual, with a high-activity group |\n| Lookback | a window per index from the `start` and `stop` columns | a fixed window through the `truncate` argument; reach set by the `network` and `stop` columns |\n| Intervention | quarantine, a multiplier on transmission | curative treatment, a change of status, with chains of diagnosis under PR |\n| Outcomes | attack rate, state of contacts when reached, quarantine days per infection averted | prevalence, repeat infection of cured cases and its source, partners reached and whether they are infected |\n\nThe chlamydia modeling literature uses pair models and individual-based network models ([Kretzschmar et al. 1996](https://doi.org/10.1093/oxfordjournals.aje.a008926); [Turner et al. 2006](https://doi.org/10.1186/1742-4682-3-3); [Althaus et al. 2012](https://doi.org/10.1371/journal.pone.0051438)), and EpiModel has been used for EPT among men who have sex with men ([Weiss et al. 2019](https://doi.org/10.1097/OLQ.0000000000001058)). This example is a template in that tradition. Its parameters are illustrative, taken from the literature where it offers a value and tuned where it does not, and it is not calibrated to any population.\n:::\n\n::: {.callout-tip}\n## Download and run the standalone scripts\n\n- [model.R](model.R): main simulation script\n- [module-fx.R](module-fx.R): custom module functions\n\n`model.R` sources `module-fx.R` from `examples/sis-partner-notification/` when run from the repository root and from the working directory otherwise, so the two downloaded files can sit in one folder. Sourcing the script interactively (for example in RStudio) uses the full settings on this page (`N = 10000`, ten simulations, a 10-year burn-in and 5 years of scenarios, about five minutes on five cores). `Rscript` is not interactive and uses the small continuous-integration settings (`N = 1000`, one simulation, a 1-year burn-in, under a minute) whose results are not meant to be interpreted; to get the full settings from the command line, pass R code that defines `run_full` as the first argument:\n\n```bash\nRscript model.R \"run_full <- TRUE\"\n```\n:::\n\n## Model Structure\n\n### Infection and care\n\n| Status | Description |\n|---|---|\n| **S** | Susceptible; reinfection is possible at any time |\n| **I** | Infected; symptomatic (`symp = 1`) or asymptomatic (`symp = 0`) for the whole infection |\n\n```{mermaid}\n%%| echo: false\nflowchart LR\n    S[\"<b>S</b><br/>Susceptible\"] -->|\"infection\"| I[\"<b>I</b><br/>Infected\"]\n    I -->|\"natural clearance\"| S\n    I -->|\"diagnosis and cure<br/>(test.FUN)\"| S\n    I -->|\"treatment as a<br/>notified partner<br/>(notify.FUN)\"| S\n    I -.->|\"diagnosis queues<br/>the index\"| PN[\"partner services<br/>get_partners() over<br/>the lookback window\"]\n\n    style S fill:#3498db,color:#fff\n    style I fill:#e74c3c,color:#fff\n    style PN fill:#5b3a8c,color:#fff\n```\n\nThere are three paths from I back to S, and none of them confers immunity. Untreated infections clear on their own after 70 weeks on average. Asymptomatic infections are found by screening, at a weekly rate that corresponds to 40% of women and 8% of men tested each year; symptomatic infections come to care after 4 weeks on average. A diagnosed case is treated, is cured with probability 0.95, and is queued for partner services. The third path is treatment as a notified partner.\n\n### Partner services\n\nFor each diagnosed case (the index), the `notify` module reads the partners of the last `pn.lookback` weeks from the cumulative edgelist of both layers and reaches each one with a probability set by the kind of partnership: an ongoing main partnership, an ongoing casual partnership, or a partnership that ended within the window. Reached partners are treated whether or not they are infected, as CDC guidance recommends. The two arms differ in three ways:\n\n- **Patient referral (PR).** A reached partner comes in the following week and is tested and treated. A partner who is infected is diagnosed and becomes an index in turn, so partners of partners are notified.\n- **Expedited partner therapy (EPT).** A reached partner takes medication delivered by the index the same week. The partner is never tested, so an infected partner is not diagnosed and the chain stops. The reach probabilities are higher than under PR.\n- **No partner services.** Diagnosed cases are treated and nothing else happens.\n\n### Node attributes\n\n| Attribute | Set by | Meaning |\n|---|---|---|\n| `sex` | network | `\"F\"` or `\"M\"`; both layers allow only female-male partnerships |\n| `risk` | network | `\"H\"` for the 10% of people with high casual-partner activity, `\"L\"` otherwise |\n| `symp` | `init_attrs`, `infect` | 1 if the current infection is symptomatic, 0 if not |\n| `dx.time` | `test_treat`, `notify` | step of the most recent diagnosis |\n| `tx.time` | `test_treat`, `infect` | step of the most recent cure after diagnosis by screening or care-seeking; starts the 13-week repeat infection clock and is cleared at the first repeat infection |\n| `pn.pending` | `test_treat`, `notify` | 1 while a diagnosed case waits for partner services |\n| `pr.visit` | `notify` | step on which a partner referred by an index comes in (PR only) |\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages(library(EpiModel))\n\n# These are the full settings of the standalone model.R. The population is\n# large enough that partner services handle a few hundred indices a year, and\n# ten simulations of each scenario resume ten burn-in simulations.\nN <- 10000\nnsims <- 10\nncores <- 5\nburnin <- 520\nhorizon <- 260\n```\n:::\n\n\n## Network Model\n\nThe population stands for sexually active heterosexual people aged roughly 15 to 24. Each time step is one week, and people leave at a rate of 1/520 per week, a mean of 10 years in the age band, with arrivals balancing departures. Partnerships are in two layers:\n\n- **Main partnerships.** Half the population is in one at any time, nobody has two at once, and they last 78 weeks on average.\n- **Casual partnerships.** They last 8 weeks on average. The 10% of people in the high-activity group have a mean of 0.5 casual partners at any time, about three new casual partners a year, and everyone else has 0.04. Half of the casual partnerships of high-activity people are with each other.\n\nThe high-activity group is what lets the infection persist at realistic numbers of partners. In versions of the model without it, the infection persisted only with a transmission probability near the top of the published range and with about half the population having two or more partners a year, against 20% to 35% in surveys. A small group with many partners keeps the infection endemic while most of the population has few, which is the core-group argument in its original form ([Yorke et al. 1978](https://doi.org/10.1097/00007435-197804000-00003)).\n\nThree EpiModel details matter here. Both layers forbid same-sex partnerships with `offset(nodematch(\"sex\"))`, and the main layer forbids a second main partnership with `offset(concurrent)`; offset terms with a coefficient of `-Inf` are hard constraints. Every attribute that either layer uses is set on the network before the first layer is estimated, because `netsim()` copies node attributes from the first network only; setting `risk` after estimating the main layer leaves the casual layer without it and fails in the first week of the simulation. And `dissolution_coefs()` takes the departure rate, so that partnerships ended by departure are counted toward their mean duration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\nnw <- network_initialize(N)\nnw <- set_vertex_attribute(nw, \"sex\", rep(c(\"F\", \"M\"), length.out = N))\nrisk <- ifelse(seq_len(N) <= 0.1 * N, \"H\", \"L\")\nnw <- set_vertex_attribute(nw, \"risk\", risk)\n\ndeparture_rate <- 1 / 520\n\nformation_main <- ~edges + offset(nodematch(\"sex\")) + offset(concurrent)\ntarget_main <- 0.5 * N / 2\ndiss_main <- dissolution_coefs(~offset(edges), duration = 78,\n                               d.rate = departure_rate)\nest_main <- netest(nw, formation_main, target_main, diss_main,\n                   coef.form = c(-Inf, -Inf), verbose = FALSE)\n\nn_high <- sum(risk == \"H\")\ndeg_high <- 0.5\ndeg_low <- 0.04\nformation_cas <- ~edges + offset(nodematch(\"sex\")) +\n  nodefactor(\"risk\", levels = \"H\") + nodematch(\"risk\", diff = TRUE, levels = \"H\")\ntarget_cas <- round(c((n_high * deg_high + (N - n_high) * deg_low) / 2,  # <1>\n                      n_high * deg_high,\n                      0.5 * n_high * deg_high / 2))\ndiss_cas <- dissolution_coefs(~offset(edges), duration = 8,\n                              d.rate = departure_rate)\nest_cas <- netest(nw, formation_cas, target_cas, diss_cas,\n                  coef.form = -Inf, verbose = FALSE)\n```\n:::\n\n1. The three targets are the number of casual partnerships, the number of partnership ends that belong to high-activity people (`nodefactor`), and the number of partnerships between two high-activity people (`nodematch`). Half of the high-activity ends are in high-high partnerships, and each of those uses two ends.\n\n### Diagnostics\n\nThe dynamic diagnostics simulate each layer on its own for five years and compare its statistics with the targets. Both runs give `tergm` a longer Markov chain than its default, for the reason explained in the lesson that follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntergm_ctrl <- control.simulate.formula.tergm(MCMC.burnin.min = 1e5)\ndx_main <- netdx(est_main, nsims = 5, ncores = ncores, nsteps = 260,\n                 nwstats.formula = ~edges + concurrent,\n                 set.control.tergm = tergm_ctrl, verbose = FALSE)\ndx_cas <- netdx(est_cas, nsims = 5, ncores = ncores, nsteps = 260,\n                nwstats.formula = ~edges + nodefactor(\"risk\", levels = TRUE) +\n                  nodematch(\"risk\", diff = TRUE, levels = \"H\"),\n                set.control.tergm = tergm_ctrl, verbose = FALSE)\nprint(dx_main)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpiModel Network Diagnostics\n=======================\nDiagnostic Method: Dynamic\nSimulations: 5\nTime Steps per Sim: 260\n\nFormation Diagnostics\n----------------------- \n           Target Sim Mean Pct Diff Sim SE Z Score SD(Sim Means) SD(Statistic)\nedges        2500 2481.681   -0.733  3.355   -5.46         10.94        24.859\nconcurrent     NA    0.000       NA    NaN      NA          0.00         0.000\n\nDuration Diagnostics\n----------------------- \n      Target Sim Mean Pct Diff Sim SE Z Score SD(Sim Means) SD(Statistic)\nedges     78   77.559   -0.566  0.217   -2.03         0.654         1.187\n\nDissolution Diagnostics\n----------------------- \n      Target Sim Mean Pct Diff Sim SE Z Score SD(Sim Means) SD(Statistic)\nedges  0.013    0.013    0.157      0    0.33             0         0.002\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(dx_cas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEpiModel Network Diagnostics\n=======================\nDiagnostic Method: Dynamic\nSimulations: 5\nTime Steps per Sim: 260\n\nFormation Diagnostics\n----------------------- \n                  Target Sim Mean Pct Diff Sim SE Z Score SD(Sim Means)\nedges                430  431.958    0.455  1.785   1.097         5.214\nnodefactor.risk.H    500  502.363    0.473  2.409   0.981         7.377\nnodefactor.risk.L     NA  361.552       NA  2.201      NA         4.502\nnodematch.risk.H     125  126.294    1.035  1.178   1.098         2.774\n                  SD(Statistic)\nedges                    19.300\nnodefactor.risk.H        26.153\nnodefactor.risk.L        21.531\nnodematch.risk.H         11.586\n\nDuration Diagnostics\n----------------------- \n      Target Sim Mean Pct Diff Sim SE Z Score SD(Sim Means) SD(Statistic)\nedges      8    8.045    0.556   0.04   1.125         0.054         0.359\n\nDissolution Diagnostics\n----------------------- \n      Target Sim Mean Pct Diff Sim SE Z Score SD(Sim Means) SD(Statistic)\nedges  0.125    0.124   -0.552      0   -1.55         0.001         0.016\n```\n\n\n:::\n\n```{.r .cell-code}\nnws <- colMeans(get_nwstats(dx_cas)[, c(\"nodefactor.risk.H\", \"nodefactor.risk.L\",\n                                        \"nodematch.risk.H\")])\ndeg_tbl <- data.frame(\n  Quantity = c(\"Mean casual degree, high activity\",\n               \"Mean casual degree, everyone else\",\n               \"High-activity casual partnerships with each other (%)\"),\n  Target = as.character(c(deg_high, deg_low, 50)),\n  Simulated = as.character(c(round(nws[[\"nodefactor.risk.H\"]] / n_high, 3),\n                             round(nws[[\"nodefactor.risk.L\"]] / (N - n_high), 3),\n                             round(100 * 2 * nws[[\"nodematch.risk.H\"]] /\n                                     nws[[\"nodefactor.risk.H\"]], 1)))\n)\nknitr::kable(deg_tbl, caption = \"Casual layer: realized degree by activity group and assortative mixing, dynamic diagnostics over five simulated years\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Casual layer: realized degree by activity group and assortative mixing, dynamic diagnostics over five simulated years\n\n|Quantity                                              |Target |Simulated |\n|:-----------------------------------------------------|:------|:---------|\n|Mean casual degree, high activity                     |0.5    |0.502     |\n|Mean casual degree, everyone else                     |0.04   |0.04      |\n|High-activity casual partnerships with each other (%) |50     |50.3      |\n\n\n:::\n:::\n\n\n### Lesson: lengthen tergm's Markov chain for short, concentrated partnerships\n\n::: {.callout-tip}\n## Set `MCMC.burnin.min` when a layer has short partnerships\n\n`tergm` draws each week's network with a Markov chain that starts from the previous week's network and stops after `MCMC.burnin.min` proposals (1,000 by default), unless its convergence check asks for more, up to `MCMC.burnin.max` (100,000 by default). A layer with short partnerships replaces many of them every week, and when those partnerships are concentrated in a small group, the default chain stops before the week's network has caught up with the model. The layer then settles below its targets. The fit is not at fault: static diagnostics, which draw each network from scratch, come close to the targets, so only a dynamic diagnostic shows the problem, and the shortfall grows with population size. The fix is one control setting, passed to both `netdx()` and `netsim()`:\n\n```r\ntergm_ctrl <- control.simulate.formula.tergm(MCMC.burnin.min = 1e5)\nnetdx(est, ..., set.control.tergm = tergm_ctrl)\ncontrol.net(..., set.control.tergm = tergm_ctrl)\n```\n\nWith `MCMC.burnin.max` also at 100,000, this fixes the chain at 100,000 proposals a week. Here it adds roughly a fifth to the run time of the epidemic simulation. Run a dynamic diagnostic, and compare it with the targets, whenever a layer has short partnerships or a small, active subgroup.\n:::\n\nThe comparison below runs the casual-layer diagnostic again with the default chain.\n\n\n::: {#tbl-chain .cell}\n\n```{.r .cell-code}\ndx_cas_default <- netdx(est_cas, nsims = 5, ncores = ncores, nsteps = 260,\n                        nwstats.formula = ~edges +\n                          nodefactor(\"risk\", levels = \"H\") +\n                          nodematch(\"risk\", diff = TRUE, levels = \"H\"),\n                        verbose = FALSE)\nstat_names <- c(\"edges\", \"nodefactor.risk.H\", \"nodematch.risk.H\")\nchain_mean <- function(dx) colMeans(get_nwstats(dx)[, stat_names])\npct_off <- function(m) sprintf(\"%.0f (%+.0f%%)\", m, 100 * (m / target_cas - 1))\nchain_tbl <- data.frame(\n  Statistic = c(\"Casual partnerships\", \"Casual partnership ends, high activity\",\n                \"Casual partnerships, high with high\"),\n  Target = target_cas,\n  `Default chain` = pct_off(chain_mean(dx_cas_default)),\n  `MCMC.burnin.min = 1e5` = pct_off(chain_mean(dx_cas)),\n  check.names = FALSE, row.names = NULL\n)\nknitr::kable(chain_tbl, caption = \"Casual layer: mean simulated statistic over five dynamic simulations of five years (percent difference from target), with tergm's default Markov chain and with MCMC.burnin.min = 1e5\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Casual layer: mean simulated statistic over five dynamic simulations of five years (percent difference from target), with tergm's default Markov chain and with MCMC.burnin.min = 1e5\n\n|Statistic                              | Target|Default chain |MCMC.burnin.min = 1e5 |\n|:--------------------------------------|------:|:-------------|:---------------------|\n|Casual partnerships                    |    430|344 (-20%)    |432 (+0%)             |\n|Casual partnership ends, high activity |    500|338 (-32%)    |502 (+0%)             |\n|Casual partnerships, high with high    |    125|49 (-61%)     |126 (+1%)             |\n\n\n:::\n:::\n\n\nWith the default chain the casual layer has 20% fewer partnerships than its target and 61% fewer partnerships between two high-activity people, the ones that carry the infection through the core group. With the longer chain every statistic is within a few percent of its target. An epidemic simulated on the default network would have had a smaller and less connected core group than the model specifies, and every result below would have inherited that error.\n\n## Custom Modules\n\nSeven modules: `init_attrs` (one-shot setup of the custom attributes), `infect` (transmission across both layers, with the repeat infection record), `test_treat` (screening, care-seeking, cure, and the queue for partner services), `notify` (partner services), `clear` (natural clearance), and `depart` and `arrive` (the open population). Full code is in `module-fx.R`; the parts that carry the logic are below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"module-fx.R\")\n```\n:::\n\n\n### `notify`: the cumulative-edgelist pattern\n\n```r\n# 1. PR: partners referred last week come in, are tested, and are treated\nvisit <- which(active == 1 & pr.visit == at)                           # <1>\ninf <- visit[status[visit] == \"i\"]\ncured <- inf[rbinom(length(inf), 1, tx.prob) == 1]\nstatus[cured] <- \"s\"\ndx.time[inf] <- at\npn.pending[inf] <- 1L\n\n# 2. Indices: everyone in the queue, including partners diagnosed in step 1\nidsIndex <- which(active == 1 & pn.pending == 1)\npn.pending[idsIndex] <- 0L\n\n# 3. Partners in the lookback window, from both layers\npart_df <- get_partners(dat, idsIndex, truncate = pn.lookback,\n                        only.active.nodes = TRUE)                       # <2>\n\n# 4. Partner unique ids back to positional ids, one row per partner\npart_df$pid <- get_posit_ids(dat, part_df$partner)                     # <3>\npart_df <- part_df[order(!is.na(part_df$stop)), ]\npart_df <- part_df[!duplicated(part_df$pid), ]\ntype <- ifelse(!is.na(part_df$stop), \"ended\",\n               ifelse(part_df$network == 1, \"main\", \"cas\"))            # <4>\nin_care <- !is.na(dx.time[part_df$pid]) & dx.time[part_df$pid] >= at - 1\npart_df <- part_df[!in_care, ]\ntype <- type[!in_care]\n\n# 5. Reach each partner with the probability for its partnership type\nreached <- rbinom(nrow(part_df), 1, reach[type]) == 1\npid <- part_df$pid[reached]\ninfected <- status[pid] == \"i\"\n\n# 6. EPT: treated now. PR: booked to come in next week.\nif (pn.arm == \"EPT\") {\n  inf <- pid[infected]\n  cured <- inf[rbinom(length(inf), 1, tx.prob) == 1]                    # <5>\n  status[cured] <- \"s\"\n} else if (pn.arm == \"PR\") {\n  pr.visit[pid] <- at + 1\n}\n```\n1. **A queue instead of a timer.** Partners booked under PR the week before are handled first. The infected ones are diagnosed and flagged in `pn.pending`, so step 2 of the same call picks them up as indices and their partners are notified this week. Chains of diagnosis advance one generation a week with no further code. (The contact tracing example times its trace by comparing the step with `dx.time`; a flag is simpler when an index can be created in several places.)\n2. **`truncate` for a fixed lookback.** `get_partners()` takes the indices as positional ids and returns their partnerships with `index` and `partner` as unique ids. `truncate = K` returns ongoing partnerships plus those last active within the past `K` steps, which is the right tool when every index has the same window: 9 weeks is the CDC's 60 days, 26 weeks is six months, and 0 returns ongoing partnerships only. Each returned row carries `index`, `partner`, `start`, `stop`, and `network`. `only.active.nodes = TRUE` drops partners who have left the population, which in this open population is a real filter: a partner who has aged out cannot be notified, and without the filter `get_posit_ids()` returns `NA` for them with a warning.\n3. **The id round trip carries weight here.** With `tergmLite = TRUE`, departed nodes are deleted at the end of each step, and the positional id of everyone after them shifts down, so a positional id stored a month ago may now point to someone else. The cumulative edgelist stores unique ids, which never change, and `get_posit_ids()` translates them to today's positions. A partner found through two indices or two layers keeps one row, the ongoing partnership first. Partners diagnosed this week or last are counted as found but not contacted, because they are already in care; this also keeps a partner diagnosed through PR from notifying the index who referred them.\n4. **The two columns that set reach.** `network` is 1 for a main and 2 for a casual partnership, and `stop` is `NA` while a partnership is ongoing, so the two columns classify every partner as ongoing main, ongoing casual, or ended.\n5. **Presumptive treatment.** Every reached partner is treated, but only an infected one changes state. The module counts reached partners by type and infection status, so the analysis can report how many treatments went to uninfected partners. Under PR the same happens at the visit a week later.\n\n### `infect`: when did the transmitting partnership begin?\n\nTransmission runs across the discordant pairs of both layers, `discord_edgelist(dat, at, network = k, include.network = TRUE)` for `k` in 1 and 2, at the same weekly probability in every partnership. The part that is specific to this example is the repeat infection record:\n\n```r\nrep_inf <- !is.na(tx.time[new]) & at - tx.time[new] <= reinf.window    # <1>\nn_reinf <- sum(rep_inf)\nif (n_reinf > 0) {\n  src <- data.frame(index = unique_id[new[rep_inf]],\n                    partner = unique_id[del$inf[rep_inf]],\n                    network = del$network[rep_inf],\n                    tx.time = tx.time[new[rep_inf]])\n  part_df <- get_partners(dat, new[rep_inf], truncate = 0)              # <2>\n  src <- merge(src, part_df, by = c(\"index\", \"partner\", \"network\"))\n  n_reinf_prior <- sum(src$start <= src$tx.time)                        # <3>\n}\n```\n1. **The clock.** `tx.time` is set when a case diagnosed by screening or care-seeking is cured, which matches the index patients of the trials, and `reinf.window = 13` weeks matches the CDC advice to retest three months after treatment. The clock is cleared at the first repeat infection, so each cure contributes at most one.\n2. **Ongoing partnerships only.** The partnership that just transmitted is by definition ongoing, and `truncate = 0` returns exactly those. The merge keys include the layer, because the same two people can be partners in both layers.\n3. **The split.** `start` is the step on which a partnership first appeared. A start at or before the cure means the person was reinfected by someone who was already their partner when they were treated.\n\n### `test_treat`, `clear`, `depart`, and `arrive`\n\n`test_treat` draws each infected person's diagnosis at the symptomatic care-seeking rate or the screening rate for their sex, cures the diagnosed with probability `tx.prob`, sets `tx.time` for the cured, and queues every diagnosed case with `pn.pending`. Partners diagnosed at a PR visit are counted separately, in `notify`. Tests of uninfected people change nothing in the model and are not simulated. `clear` returns untreated infections to S at `rec.rate`. `depart` removes people at `departure.rate`, and `arrive` adds susceptible people at the same rate and extends every custom attribute; it does not set `sex` or `risk`, because both are vertex attributes of the network, and EpiModel assigns such attributes to arrivals itself, here from the proportions at the start because `control.net()` sets `attr.rules = list(sex = \"t1\", risk = \"t1\")`. `init_attrs` creates the custom attributes only if `dx.time` does not exist yet, which is what lets a resumed run keep the burn-in's attributes.\n\n### Module order\n\nEpiModel's default order runs user-supplied modules before the built-in ones, which would put `test` and `notify` ahead of `resim_nets`, where the cumulative edgelist is updated. The order is set explicitly in `control.net()` so that each week runs\n\n```\nresim_nets -> summary_nets -> initAttr -> infection -> test -> notify ->\n    recovery -> departures -> arrivals -> nwupdate -> prevalence\n```\n\nWith this order the partnership history includes the week's partnerships when `notify` reads it, the week's diagnoses are queued before partner services run, and people who leave this week are still present, and reachable, when their partners are notified. A module left out of `module.order` is skipped; `control.net()` warns only when `resim_nets`, `summary_nets`, or `nwupdate` is missing.\n\n## Parameters\n\n**Natural history.** Untreated infections clear after 70 weeks on average, between the 1.35 years estimated for women by an evidence synthesis ([Lewis et al. 2017](https://doi.org/10.1093/infdis/jix283)) and the 433 days for asymptomatic women of [Althaus et al. 2010](https://doi.org/10.1016/j.epidem.2010.04.002); the estimate for men in the synthesis is longer but imprecise (2.84 years, 0.87 to 18.79). Ten percent of infections in women and 20% in men are symptomatic, assumed values in a range where the evidence is weak ([Davies et al. 2014](https://doi.org/10.1186/1742-4682-11-8); 77% asymptomatic in [Farley et al. 2003](https://doi.org/10.1016/s0091-7435(02)00058-0)), and symptomatic infections come to care after 4 weeks on average.\n\n**Transmission.** Every partnership has one act of intercourse a week, near the four per four weeks reported in Natsal-3 ([Mercer et al. 2013](https://doi.org/10.1016/S0140-6736(13)62035-8)), with a transmission probability of 0.11 per act. That is inside the range estimated from couples data (0.10, interquartile range 0.06 to 0.17; [Althaus, Heijne, and Low 2012](https://doi.org/10.1097/OLQ.0b013e318248a550)) and the 9% to 15% per act of an individual-based model calibrated to 3% prevalence in Britain (Althaus et al. 2012). It was tuned so that prevalence under the standard of care settles near 3%. It is the same in both directions, as in the couples data of [Quinn et al. 1996](https://pubmed.ncbi.nlm.nih.gov/8940322/); syntheses of survey data suggest that male-to-female transmission is more likely ([Lewis, White, and Price 2021](https://doi.org/10.1093/ije/dyaa202)).\n\n**Testing and treatment.** Forty percent of women and 8% of men are tested each year. The first sits between self-reported testing among women aged 15 to 24 in the National Survey of Family Growth (37.5%; [Pazol et al. 2017](https://doi.org/10.15585/mmwr.ss6620a1)) and screening of insured sexually active women aged 16 to 24 (48% to 58%; [He et al. 2023](https://doi.org/10.1097/OLQ.0000000000001809)). Treatment cures 95% of infections (97% for azithromycin and 100% for doxycycline in [Geisler et al. 2015](https://doi.org/10.1056/NEJMoa1502599)).\n\n**Partner services.** Under PR an ongoing main partner is reached with probability 0.45, an ongoing casual partner with 0.20, and a partner whose partnership has ended with 0.10, which gives about 0.35 partners treated per index. In the United States, patient referral is mostly left to the patient, few health departments provide partner services for chlamydia (CDC 2021; in 1998, 12% of chlamydia cases in high-morbidity areas were interviewed for partner notification, [Golden et al. 2003](https://doi.org/10.1097/00007435-200306000-00004)), and US models fit partner treatment near 25% ([Kretzschmar et al. 2012](https://doi.org/10.1097/OLQ.0b013e31824e52c2)). UK clinics with health advisers reach a median of 0.60 partners treated per index ([Althaus et al. 2014](https://doi.org/10.3310/hta18020)). The ordering by partnership type follows program data: 74% of current regular partners were seen against 12% to 13% of former regular and casual partners in [Patel et al. 1994](https://doi.org/10.1177/095646249400500403), and 58% of established against 21% of one-off partners were tested in [McMahon et al. 2025](https://doi.org/10.1136/sextrans-2024-056108). EPT adds 20, 15, and 5 percentage points. In the trials, all partners were treated for 61% of index patients under EPT against 49% under standard referral (Golden 2005), women with one partner reported that the partner was very likely treated in 86% against 57% (Schillinger 2003, as summarized in [CDC 2006](https://stacks.cdc.gov/view/cdc/6804)), and index men reported that their partners took medication in 56% against 35% ([Kissinger et al. 2005](https://doi.org/10.1086/432476)); the Cochrane review found 0.43 more partners treated per index (Ferreira 2013).\n\n::: {.callout-important}\n## Simplifications\n\n- **No change in behavior after diagnosis.** A cured index keeps having sex with every ongoing partner every week, treated or not. CDC guidance asks patients to abstain until their partners are treated, and in the Golden trial 22% of women with chlamydia reported no sex at all after treatment, and 12% under standard referral reported sex with a partner who had not been treated ([CDC 2006](https://stacks.cdc.gov/view/cdc/6804)). Repeat infection in the model is therefore about twice the 10% to 17% observed ([Hosenfeld et al. 2009](https://doi.org/10.1097/OLQ.0b013e3181a2a933); [Fung et al. 2007](https://doi.org/10.1136/sti.2006.024059)), and the part of partner notification's benefit that comes from protecting the index is an upper bound.\n- **Every index accepts EPT.** In practice acceptance is the limiting step: a median of 65% in a systematic review ([Layton et al. 2020](https://doi.org/10.1097/OLQ.0000000000001260)) and 19% of index patients chose accelerated partner therapy, the UK form of EPT, in the LUSTRUM trial ([Estcourt et al. 2022](https://doi.org/10.1016/S2468-2667(22)00204-3)). The EPT scenarios describe a program in which every index takes it.\n- **No age structure.** The model has no age-disparate partnerships, which is one reason why women and men have similar prevalence here although young women have higher prevalence in NHANES.\n- **Partner services have no capacity limit and fixed timing:** the same week under EPT and the following week under PR.\n- **Treatment is presumptive.** The 2026 BASHH guideline tests asymptomatic contacts who present more than 14 days after exposure before treating them ([Saunders et al. 2026](https://doi.org/10.1177/09564624261475950)); the model has no test-first option.\n:::\n\n### Parameter provenance\n\n| Parameter | Value | Meaning | Basis | Status |\n|---|---|---|---|---|\n| main layer | 50% in a main partnership; 78 weeks; none concurrent | ongoing partnerships | 62% to 67% in a partnership at any time in Natsal-2 (Althaus 2012); US data do not separate main and casual partnerships at these ages | assumed |\n| casual layer | 8 weeks; mean degree 0.5 (high activity) and 0.04 (others); half of high-activity partnerships with each other | short partnerships and a core group | median 1.6 months after adjusting for sampling bias ([Burington et al. 2010](https://doi.org/10.1136/sti.2009.037960)); degrees tuned to the partner-count targets | tuned |\n| `departure.rate` | 1/520 per week | 10 years in the 15 to 24 age band | design | design |\n| `inf.prob` | 0.11 | per-act, per-week transmission probability | 0.10 (0.06 to 0.17) per act (Althaus, Heijne, Low 2012); tuned to about 3% prevalence | tuned |\n| `rec.rate` | 1/70 per week | natural clearance | 1.35 years in women (Lewis 2017); 433 days (Althaus 2010) | literature |\n| `symp.prob.f`, `symp.prob.m` | 0.1, 0.2 | share of infections that are symptomatic | weak evidence (Davies 2014; Farley 2003) | assumed |\n| `symp.test.rate` | 0.25 per week | symptomatic care-seeking, mean 4 weeks | symptomatic infection lasts 30 to 40 days before treatment in published models (Davies 2014) | assumed |\n| `screen.rate.f`, `screen.rate.m` | 40% and 8% per year | screening of asymptomatic infections | Pazol 2017; He 2023; men assumed | literature, assumed |\n| `tx.prob` | 0.95 | cure after treatment | Geisler 2015; [Kong et al. 2014](https://doi.org/10.1093/cid/ciu220) | literature |\n| `reinf.window` | 13 weeks | follow-up for repeat infection | CDC advice to retest at three months | policy |\n| `pn.lookback` | 9, 26, or 0 weeks | lookback window | CDC 60 days; UK six months; ongoing partners only | scenario |\n| `reach.main`, `reach.cas`, `reach.ended` | PR 0.45, 0.20, 0.10; EPT 0.65, 0.35, 0.15 | probability of reaching and treating a partner | Kretzschmar 2012; Althaus 2014; Patel 1994; McMahon 2025; EPT differences from the trials (Golden 2005; Schillinger 2003; Kissinger 2005; Ferreira 2013) | assumed, scenario |\n| `N`, `burnin`, `horizon`, seeds | 10,000; 520 weeks; 260 weeks; 4% infected at the start | population and run length | long enough for the burn-in to forget its start; 10 simulations per scenario | design |\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparam_base <- param.net(\n  inf.prob = 0.11,\n  rec.rate = 1 / 70,\n  symp.prob.f = 0.1,\n  symp.prob.m = 0.2,\n  symp.test.rate = 0.25,\n  screen.rate.f = 1 - (1 - 0.4)^(1 / 52),                              # <1>\n  screen.rate.m = 1 - (1 - 0.08)^(1 / 52),\n  tx.prob = 0.95,\n  reinf.window = 13,\n  pn.arm = \"PR\",                                                        # <2>\n  pn.lookback = 9,\n  reach.main = 0.45,\n  reach.cas = 0.20,\n  reach.ended = 0.10,\n  departure.rate = departure_rate,\n  arrival.rate = departure_rate\n)\n\ninit <- init.net(i.num = round(0.04 * N))\n```\n:::\n\n1. An annual probability converted to the weekly probability that gives the same chance of a test within a year.\n2. The base set is patient referral with a 60-day lookback, the standard of care the burn-in runs; the scenarios change it.\n\n## Control Settings\n\nThe burn-in and the scenarios use the same controls and differ only in the steps they run and in what they keep, so the controls are built by one function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_control <- function(start, nsteps, save) {\n  control.net(\n    type = NULL,\n    nsims = nsims,\n    ncores = ncores,\n    start = start,                                                      # <1>\n    nsteps = nsteps,\n    tergmLite = TRUE,                                                   # <2>\n    resimulate.network = TRUE,\n    cumulative.edgelist = TRUE,                                         # <3>\n    truncate.el.cuml = 52,                                              # <4>\n    initAttr.FUN = init_attrs,\n    infection.FUN = infect,\n    test.FUN = test_treat,\n    notify.FUN = notify,\n    recovery.FUN = clear,\n    departures.FUN = depart,\n    arrivals.FUN = arrive,\n    module.order = c(\"resim_nets.FUN\", \"summary_nets.FUN\", \"initAttr.FUN\",\n                     \"infection.FUN\", \"test.FUN\", \"notify.FUN\",\n                     \"recovery.FUN\", \"departures.FUN\", \"arrivals.FUN\",\n                     \"nwupdate.FUN\", \"prevalence.FUN\"),\n    attr.rules = list(sex = \"t1\", risk = \"t1\"),                         # <5>\n    epi.by = \"sex\",                                                     # <6>\n    set.control.tergm = tergm_ctrl,                                     # <7>\n    save.run = save,                                                    # <8>\n    save.cumulative.edgelist = save,\n    verbose = FALSE\n  )\n}\n```\n:::\n\n1. `start` is 1 for the burn-in and the first week after it for the scenarios.\n2. `tergmLite = TRUE` stores each layer as an edgelist and makes each step several times faster. It is also what deletes departed nodes, which is why the id round trip in `notify` matters.\n3. Required. Without this switch no partnership history is kept, and `get_partners()` stops with an error.\n4. Partnerships that ended more than 52 weeks ago are dropped from memory. The value must be at least the longest window a module asks for (26 weeks); it is 52 so that the analysis can count each person's partners over the past year. The default of 0 records no ended partnerships at all (see the [contact tracing example](../seir-contact-tracing/)).\n5. Arrivals get a sex and an activity group drawn from the proportions at the start of the simulation. Without this line EpiModel draws them from the current proportions.\n6. Prevalence is recorded by sex as well as overall (`i.num.sexF`, `num.sexM`, and so on).\n7. The longer Markov chain from the lesson above.\n8. For the burn-in only: `save.run = TRUE` keeps the complete state of every simulation (attributes, networks, and the cumulative edgelist) so that it can be resumed, and `save.cumulative.edgelist = TRUE` returns the partnership history for analysis.\n\n## Burn-in to Endemic Equilibrium\n\nAn endemic model has to forget where it started. The burn-in runs ten years of screening with patient referral from a start in which 4% of the population is infected. It is run once, and every scenario resumes it, which saves four burn-ins and gives every scenario the same starting states.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2027)\nsim_burnin <- netsim(list(est_main, est_cas), param_base, init,\n                     make_control(start = 1, nsteps = burnin, save = TRUE))\n\nepi_df <- function(sim) {                                               # <1>\n  df <- as.data.frame(sim)\n  df$time <- ave(df$time, df$sim, FUN = seq_along)\n  df\n}\n```\n:::\n\n1. In EpiModel 2.6.2, `as.data.frame()` numbers the steps of a resumed simulation from its `start` step although the output also holds the burn-in history, so every step is labeled `start - 1` too late. The helper numbers the steps by position, which is correct whether or not the labels are fixed.\n\nThe burn-in is compared with published targets over its last two years. The partner counts come from the saved cumulative edgelist, one data frame per simulation with both layers and unique ids, which makes it an analysis tool as well as a modeling one.\n\n\n::: {#tbl-calibration .cell}\n\n```{.r .cell-code}\nbdf <- epi_df(sim_burnin)\nbdf <- bdf[bdf$time > burnin - 104, ]\ntot <- function(x) sum(x, na.rm = TRUE)\n\npartners_past_year <- sapply(seq_len(nsims), function(s) {\n  el <- sim_burnin$cumulative.edgelist[[s]]\n  el <- el[is.na(el$stop) | el$stop > burnin - 52, ]\n  attr <- sim_burnin$run[[s]]$attr\n  ids <- attr$unique_id[attr$entrTime <= burnin - 51]\n  n <- table(factor(c(el$head, el$tail), levels = ids))\n  c(mean = mean(n), two_plus = 100 * mean(n >= 2))\n})\n\nfound <- tot(bdf$pn.found.main.flow + bdf$pn.found.cas.flow +\n               bdf$pn.found.ended.flow)\nreached_cur <- tot(bdf$pn.reach.main.flow + bdf$pn.reach.cas.flow)\ndx_f <- tot(bdf$dx.flow.f + bdf$pn.dx.flow.f)\ndx_m <- tot(bdf$dx.flow + bdf$pn.dx.flow) - dx_f\ncalib_tbl <- data.frame(\n  Quantity = c(\"Prevalence, women (%)\", \"Prevalence, men (%)\",\n               \"New infections diagnosed, women (%)\",\n               \"New infections diagnosed, men (%)\",\n               \"Diagnoses, women per man\",\n               \"Partners in the past year, mean\",\n               \"Two or more partners in the past year (%)\",\n               \"Partners in the 60-day window per index\",\n               \"Reached ongoing partners who are infected (%)\",\n               \"Repeat infection within 13 weeks of cure (%)\"),\n  Model = sprintf(c(\"%.1f\", \"%.1f\", \"%.0f\", \"%.0f\", \"%.1f\", \"%.2f\", \"%.0f\",\n                    \"%.2f\", \"%.0f\", \"%.0f\"),\n                  c(100 * mean(bdf$i.num.sexF / bdf$num.sexF),\n                    100 * mean(bdf$i.num.sexM / bdf$num.sexM),\n                    100 * dx_f / tot(bdf$si.flow.f),\n                    100 * dx_m / tot(bdf$si.flow - bdf$si.flow.f),\n                    dx_f / dx_m,\n                    mean(partners_past_year[\"mean\", ]),\n                    mean(partners_past_year[\"two_plus\", ]),\n                    found / tot(bdf$pn.index.flow),\n                    100 * tot(bdf$pn.inf.main.flow + bdf$pn.inf.cas.flow) /\n                      reached_cur,\n                    100 * tot(bdf$reinf.flow) / tot(bdf$tx.flow))),\n  Target = c(\"4.7\", \"2.7\", \"35 to 50\", \"25 to 40\", \"about 2.5\", \"1.70\",\n             \"20 to 35\", \"1.18 to 1.48 named in 6 months\", \"50 to 75\",\n             \"10 to 17\")\n)\nknitr::kable(calib_tbl, caption = \"The burn-in under patient referral against published targets, last two years of the burn-in pooled over simulations. Sources in the text.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: The burn-in under patient referral against published targets, last two years of the burn-in pooled over simulations. Sources in the text.\n\n|Quantity                                      |Model |Target                         |\n|:---------------------------------------------|:-----|:------------------------------|\n|Prevalence, women (%)                         |3.2   |4.7                            |\n|Prevalence, men (%)                           |3.5   |2.7                            |\n|New infections diagnosed, women (%)           |51    |35 to 50                       |\n|New infections diagnosed, men (%)             |42    |25 to 40                       |\n|Diagnoses, women per man                      |1.3   |about 2.5                      |\n|Partners in the past year, mean               |1.45  |1.70                           |\n|Two or more partners in the past year (%)     |32    |20 to 35                       |\n|Partners in the 60-day window per index       |1.47  |1.18 to 1.48 named in 6 months |\n|Reached ongoing partners who are infected (%) |75    |50 to 75                       |\n|Repeat infection within 13 weeks of cure (%)  |31    |10 to 17                       |\n\n\n:::\n:::\n\n\nThe targets are, in order: prevalence among women and men aged 15 to 24 in the United States ([Kreisel et al. 2021](https://doi.org/10.1097/OLQ.0000000000001382); 4.7% among sexually active women aged 14 to 24 in NHANES, [Torrone et al. 2014](https://pubmed.ncbi.nlm.nih.gov/25254560/)); reported cases, which include diagnosed partners, as a share of estimated new infections, derived from Kreisel 2021 and CDC surveillance; the ratio of reported case rates in women and men aged 15 to 24 ([CDC 2023 surveillance](https://stacks.cdc.gov/view/cdc/255132)); partners in the past year in Natsal-2 as used by Althaus 2012, and the share with two or more partners in the National Survey of Family Growth ([Chandra et al. 2011](https://www.cdc.gov/nchs/data/nhsr/nhsr036.pdf)); partners named per index in the Public Health England audit and in LUSTRUM clinics ([Estcourt et al. 2022](https://doi.org/10.1136/sextrans-2020-054846)); infection in current partners ([Quinn 1996](https://pubmed.ncbi.nlm.nih.gov/8940322/); [Rogers et al. 2008](https://doi.org/10.1136/sti.2007.027029); Althaus 2012); and repeat infection among women and men treated for chlamydia (Hosenfeld 2009; Fung 2007).\n\nThe burn-in reproduces the share of people with two or more partners and the infection rate among current partners, comes close to the number of partners named per index, and it has somewhat fewer partners per person than the Natsal-2 figure, which comes from a sexually active British sample. Counting partners diagnosed at PR visits, 51% of new infections in women and 42% in men are diagnosed, at or above the upper end of the ranges derived from surveillance; partner referral finds men who are rarely screened. Prevalence is 3.2% in women and 3.5% in men, lower than the US estimate for women and above it for men, and women account for 1.3 diagnoses per man against about 2.5 in surveillance. Three features of the model push men's prevalence up relative to women's: women are screened five times as often as men, transmission is equally likely in both directions, and there is no age structure, so young women are not exposed to the older men with whom many of their partnerships form. The largest gap is repeat infection: 31% of cured cases are reinfected within 13 weeks, about twice the observed range, because nobody in the model abstains or changes partners after a diagnosis (see Simplifications). The comparisons of partner services strategies below are relative to this baseline, and the repeat infection results are best read as relative changes.\n\n## Scenarios Resumed from the Burn-in\n\nPassing the burn-in's `netsim` object to `netsim()` in place of the network models, with `control.net(start = burnin + 1)`, resumes each burn-in simulation where it stopped: scenario simulation *s* continues burn-in simulation *s* with the scenario's parameters. The parameters passed to the resumed run apply from its first week, and any that are missing are taken from the burn-in. Calling `set.seed()` with the same value before each scenario gives the scenarios the same random number streams from the moment they resume, so two scenarios that make identical choices produce identical epidemics, and differences between them are compared within each pair of simulations. EpiModel 2.6.2 warns once per scenario that setting row names on a tibble is deprecated when it saves a resumed simulation; the warning is harmless and is hidden here.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscenarios.df <- data.frame(\n  .scenario.id = c(\"none\", \"pr\", \"pr_6mo\", \"ept\", \"ept_cur\"),\n  .at          = 0,\n  pn.arm       = c(\"none\", \"PR\", \"PR\", \"EPT\", \"EPT\"),\n  pn.lookback  = c(9, 9, 26, 9, 0),\n  reach.main   = c(0.45, 0.45, 0.45, 0.65, 0.65),\n  reach.cas    = c(0.20, 0.20, 0.20, 0.35, 0.35),\n  reach.ended  = c(0.10, 0.10, 0.10, 0.15, 0.15)\n)\nscenarios.list <- create_scenario_list(scenarios.df)\n\nlabels <- c(none = \"No partner services\",\n            pr = \"Patient referral, 60 days\",\n            pr_6mo = \"Patient referral, 6 months\",\n            ept = \"EPT, 60 days\",\n            ept_cur = \"EPT, ongoing partners only\")\ncols <- c(none = \"gray40\", pr = \"goldenrod\", pr_6mo = \"mediumpurple\",\n          ept = \"seagreen\", ept_cur = \"steelblue\")\n\ncontrol_scn <- make_control(start = burnin + 1, nsteps = burnin + horizon,\n                            save = FALSE)\nsims <- list()\nfor (scn in scenarios.list) {\n  set.seed(2028)\n  sims[[scn$id]] <- netsim(sim_burnin, use_scenario(param_base, scn), init,\n                           control_scn)\n}\n```\n:::\n\n\nThe patient referral scenario continues the burn-in unchanged and is the comparator for the others. No partner services removes it; patient referral with six months extends its lookback to UK practice; EPT with 60 days replaces it with expedited therapy at the CDC window; and EPT for ongoing partners only restricts EPT to the partners an index is still seeing.\n\n## Analysis\n\n### Per-simulation summaries\n\nEvery quantity is summed over the five scenario years and kept one value per simulation. Because the scenarios resume the same burn-in simulations, a difference between two scenarios is taken within each simulation before it is averaged, and its 95% Monte Carlo interval comes from the spread of those paired differences, with a t quantile because there are only ten of them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntypes <- c(\"main\", \"cas\", \"ended\")\nsummarize_scenario <- function(sim) {\n  df <- epi_df(sim)\n  df <- df[df$time > burnin, ]\n  by_sim <- function(x) as.numeric(tapply(x, df$sim, sum, na.rm = TRUE))\n  by_type <- function(prefix) {\n    sapply(types, function(k) by_sim(df[[paste0(prefix, k, \".flow\")]]))\n  }\n  end_prev <- function(i, n) {\n    100 * as.numeric(tapply(i / n, df$sim, function(v) mean(tail(v, 52))))\n  }\n  list(inf = by_sim(df$si.flow),\n       prev = end_prev(df$i.num, df$num),\n       tx = by_sim(df$tx.flow),\n       index = by_sim(df$pn.index.flow),\n       found = matrix(by_type(\"pn.found.\"), ncol = 3),\n       reach = matrix(by_type(\"pn.reach.\"), ncol = 3),\n       reach_inf = matrix(by_type(\"pn.inf.\"), ncol = 3),\n       part_dx = by_sim(df$pn.dx.flow),\n       reinf = by_sim(df$reinf.flow),\n       reinf_prior = by_sim(df$reinf.prior.flow))\n}\nres <- lapply(sims, summarize_scenario)\n\nmc_mean <- function(x) {\n  m <- mean(x)\n  if (length(x) < 2) return(c(est = m, lo = NA, hi = NA))\n  half <- qt(0.975, length(x) - 1) * sd(x) / sqrt(length(x))\n  c(est = m, lo = m - half, hi = m + half)\n}\nmc_paired <- function(x0, x1) mc_mean(x0 - x1)\nfmt_ci <- function(v, digits = 1) {\n  if (is.na(v[\"lo\"])) return(sprintf(\"%.*f\", digits, v[\"est\"]))\n  sprintf(\"%.*f (%.*f, %.*f)\", digits, v[\"est\"], digits, v[\"lo\"], digits, v[\"hi\"])\n}\n```\n:::\n\n\n### Prevalence\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1), mar = c(4, 4.2, 2.5, 1), mgp = c(2.4, 0.8, 0))\nprev_t <- lapply(sims, function(sim) {\n  df <- epi_df(sim)\n  100 * tapply(df$i.num / df$num, df$time, mean)\n})\nshow <- max(1, burnin - 155):(burnin + horizon)\nplot(NA, xlim = range(show - burnin) / 52,\n     ylim = c(0, max(sapply(prev_t, max)) * 1.1),\n     xlab = \"Years since the change in partner services\",\n     ylab = \"Prevalence (%, mean of simulations)\",\n     main = \"Prevalence by Partner Services Strategy\")\nabline(v = 0, lty = 2, col = \"gray50\")\nfor (s in names(sims)) {\n  lines((show - burnin) / 52, prev_t[[s]][show], lwd = 2, col = cols[s])\n}\nlegend(\"topleft\", legend = labels, col = cols, lwd = 2, bty = \"n\", cex = 0.75)\n```\n\n::: {.cell-output-display}\n![Prevalence over the last three years of the burn-in and the five scenario years, mean of simulations, by partner services strategy. The dashed line marks the last week of the burn-in; the scenarios begin the following week.](index_files/figure-html/fig-prevalence-1.png){#fig-prevalence width=768}\n:::\n:::\n\n\n### Infections averted\n\n\n::: {#tbl-outcomes .cell}\n\n```{.r .cell-code}\nalt <- c(\"none\", \"pr_6mo\", \"ept\", \"ept_cur\")\naverted <- lapply(alt, function(s) mc_paired(res$pr$inf, res[[s]]$inf))\nnames(averted) <- alt\nadded_none <- mc_paired(res$none$inf, res$pr$inf)\nept_window <- mc_paired(res$ept_cur$inf, res$ept$inf)\ntreated <- sapply(res, function(r) mean(rowSums(r$reach)))\nout_tbl <- data.frame(\n  Scenario = labels[names(res)],\n  `Prevalence after 5 years (%)` = sapply(res, function(r) fmt_ci(mc_mean(r$prev))),\n  `New infections` = sapply(res, function(r) round(mean(r$inf))),\n  `Infections averted vs patient referral` =\n    c(fmt_ci(averted$none, 0), \"\", sapply(averted[-1], fmt_ci, digits = 0)),\n  `Percent change in infections` = sapply(res, function(r)\n    round(100 * (mean(r$inf) - mean(res$pr$inf)) / mean(res$pr$inf), 1)),\n  `Partners treated` = round(treated),\n  `Infections averted per partner treated, vs none` =\n    c(\"\", sapply(names(res)[-1], function(s)\n      sprintf(\"%.1f\", (mean(res$none$inf) - mean(res[[s]]$inf)) / treated[[s]]))),\n  check.names = FALSE, row.names = NULL\n)\nknitr::kable(out_tbl, caption = \"Prevalence in the fifth scenario year (mean of simulations with 95% Monte Carlo interval), new infections over five years, infections averted relative to patient referral (mean of paired differences with 95% Monte Carlo interval; negative values are infections added), the change in infections relative to patient referral, partners treated over five years, and infections averted per partner treated relative to no partner services\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Prevalence in the fifth scenario year (mean of simulations with 95% Monte Carlo interval), new infections over five years, infections averted relative to patient referral (mean of paired differences with 95% Monte Carlo interval; negative values are infections added), the change in infections relative to patient referral, partners treated over five years, and infections averted per partner treated relative to no partner services\n\n|Scenario                   |Prevalence after 5 years (%) | New infections|Infections averted vs patient referral | Percent change in infections| Partners treated|Infections averted per partner treated, vs none |\n|:--------------------------|:----------------------------|--------------:|:--------------------------------------|----------------------------:|----------------:|:-----------------------------------------------|\n|No partner services        |6.3 (5.0, 7.6)               |           3662|-1045 (-1420, -670)                    |                         39.9|                0|                                                |\n|Patient referral, 60 days  |3.7 (2.9, 4.5)               |           2617|                                       |                          0.0|              414|2.5                                             |\n|Patient referral, 6 months |3.0 (2.2, 3.8)               |           2335|282 (-31, 595)                         |                        -10.8|              429|3.1                                             |\n|EPT, 60 days               |2.6 (2.1, 3.1)               |           2187|430 (132, 729)                         |                        -16.4|              476|3.1                                             |\n|EPT, ongoing partners only |2.5 (2.0, 3.1)               |           2083|534 (224, 844)                         |                        -20.4|              409|3.9                                             |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1), mar = c(4, 4.5, 3, 1), mgp = c(2.6, 0.8, 0))\nshort <- c(none = \"No partner services\", pr_6mo = \"PR, 6 months\",\n           ept = \"EPT, 60 days\", ept_cur = \"EPT, ongoing only\")\nav <- sapply(averted, function(v) 1000 * v / N)\nbp <- barplot(av[\"est\", ], names.arg = short[alt], col = cols[alt],\n              ylab = \"Infections averted per 1,000 people\",\n              main = \"Five-Year Infections Averted Relative to Patient Referral\",\n              ylim = range(c(0, av), na.rm = TRUE) * 1.15, cex.names = 0.85)\nabline(h = 0)\nif (!all(is.na(av[\"lo\", ]))) {\n  arrows(bp, av[\"lo\", ], bp, av[\"hi\", ], angle = 90, code = 3, length = 0.04)\n}\n```\n\n::: {.cell-output-display}\n![Infections averted over five years per 1,000 people, relative to patient referral with a 60-day lookback, with 95% Monte Carlo intervals from the paired differences. The bar below zero is the infections added by removing partner services.](index_files/figure-html/fig-averted-1.png){#fig-averted width=768}\n:::\n:::\n\n\nRemoving partner services adds 1045 (670, 1420) infections over five years, 39.9% more than under patient referral, and prevalence in the fifth year is 6.3% against 3.7%. The curve without partner services is still rising at year five, so five-year totals understate the long-run difference; the patient referral curve, which continues the burn-in unchanged, drifts within the range of its between-simulation variation (last table). An effect of this size is consistent with the US model of [Kretzschmar et al. 2012](https://doi.org/10.1097/OLQ.0b013e31824e52c2), in which doubling the share of partners treated reduced positivity as much as tripling screening coverage, and it reflects a system held near its epidemic threshold, where a small change in the number of infections each case causes moves prevalence a long way.\n\nEPT with a 60-day window averts 430 (132, 729) infections relative to patient referral, 16.4% fewer, and EPT for ongoing partners only averts 534 (224, 844), 20.4% fewer. EPT does better although it gives up the chain of diagnosis, because it reaches more partners and treats them a week sooner (next sections). The direction matches the trials. The size is larger than in the Washington State community trial, where chlamydia positivity fell by 11% (prevalence ratio 0.89, 0.77 to 1.04) as the share of index patients given EPT rose from 18% to 34% ([Golden et al. 2015](https://doi.org/10.1371/journal.pmed.1001777)), in part because here every index accepts EPT. The ranking can reverse on networks with highly connected people, where tracing through the network finds them ([Kao and Enns 2020](https://doi.org/10.1097/OLQ.0000000000001100)); the patient referral chain here is short (next sections). The 60-day EPT program reaches the same ongoing partners as the ongoing-only program plus some whose partnerships ended within the window, so its effect should be at least as large. The paired difference, infections under the ongoing-only program minus infections under the 60-day program, is -104 (-307, 99), within Monte Carlo noise; few ended partners are reached, so the two programs differ little.\n\nExtending patient referral to six months averts 282 (-31, 595) infections, 10.8% fewer than with 60 days, an interval that includes zero. What it adds are partnerships that ended two to six months before diagnosis, which are numerous and rarely reached (next sections). Relative to no partner services, each partner treated averts 2.5 to 3.9 infections over five years, because curing an infected partner also prevents the infections that partner would have caused and the ones those would have caused in turn.\n\n### Repeat infection of cured cases\n\n\n::: {#tbl-reinfection .cell}\n\n```{.r .cell-code}\nreinf_tbl <- data.frame(\n  Scenario = labels[names(res)],\n  `Cured cases` = sapply(res, function(r) round(mean(r$tx))),\n  `Repeat infection within 13 weeks (%)` = sapply(res, function(r)\n    round(100 * sum(r$reinf) / sum(r$tx), 1)),\n  `From a partner they already had (%)` = sapply(res, function(r)\n    round(100 * sum(r$reinf_prior) / sum(r$reinf))),\n  `Relative to patient referral` = sapply(res, function(r)\n    round((sum(r$reinf) / sum(r$tx)) / (sum(res$pr$reinf) / sum(res$pr$tx)), 2)),\n  check.names = FALSE, row.names = NULL\n)\nknitr::kable(reinf_tbl, caption = \"Cases cured after diagnosis by testing over five years (mean per simulation), the share reinfected within 13 weeks of cure, the share of those repeat infections transmitted by a partner the person already had when cured, and the repeat infection proportion relative to patient referral, pooled over simulations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cases cured after diagnosis by testing over five years (mean per simulation), the share reinfected within 13 weeks of cure, the share of those repeat infections transmitted by a partner the person already had when cured, and the repeat infection proportion relative to patient referral, pooled over simulations\n\n|Scenario                   | Cured cases| Repeat infection within 13 weeks (%)| From a partner they already had (%)| Relative to patient referral|\n|:--------------------------|-----------:|------------------------------------:|-----------------------------------:|----------------------------:|\n|No partner services        |        1194|                                 45.2|                                  98|                         1.43|\n|Patient referral, 60 days  |         849|                                 31.6|                                  98|                         1.00|\n|Patient referral, 6 months |         762|                                 30.9|                                  98|                         0.98|\n|EPT, 60 days               |         719|                                 22.0|                                  97|                         0.70|\n|EPT, ongoing partners only |         684|                                 21.6|                                  97|                         0.68|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1), mar = c(4, 4.5, 3, 1), mgp = c(2.6, 0.8, 0))\nreinf <- sapply(res, function(r) {\n  100 * c(prior = sum(r$reinf_prior), new = sum(r$reinf - r$reinf_prior)) / sum(r$tx)\n})\nbarplot(reinf, names.arg = c(\"None\", \"PR, 60 days\", \"PR, 6 months\",\n                             \"EPT, 60 days\", \"EPT, ongoing\"),\n        col = c(\"firebrick\", \"gray75\"), cex.names = 0.85,\n        ylab = \"Reinfected within 13 weeks of cure (%)\",\n        main = \"Repeat Infection of Cured Cases\",\n        ylim = c(0, max(colSums(reinf)) * 1.3))\nlegend(\"topright\", fill = c(\"firebrick\", \"gray75\"), bty = \"n\", cex = 0.8,\n       legend = c(\"By a partner they had when cured\", \"By a new partner\"))\n```\n\n::: {.cell-output-display}\n![Repeat infection within 13 weeks of cure, by the source of the reinfection: a partner the person already had when cured, or a partner from a partnership that began afterward.](index_files/figure-html/fig-reinfection-1.png){#fig-reinfection width=768}\n:::\n:::\n\n\nUnder patient referral, 31.6% of cured cases are reinfected within 13 weeks, and 98% of those repeat infections come from a partner the person already had when cured; new partners account for few repeat infections within 13 weeks. EPT reduces repeat infection to 22%, a ratio of 0.7 to patient referral (0.68 for ongoing partners only). That is close to the relative risks for chlamydia and gonorrhea combined in the Golden trial (0.76, 0.59 to 0.98) and in the Cochrane review against simple patient referral (0.71, 0.56 to 0.89), and a larger reduction than the trials found for chlamydia alone (0.90, 0.60 to 1.35). The absolute levels are about twice those observed (see Simplifications). The six-month lookback leaves repeat infection unchanged, since the partners it adds cannot reinfect the index. A pair model found that treating current partners within three days of the index removes most of the reinfection risk ([Low et al. 2014](https://doi.org/10.1136/sextrans-2013-051279)); EPT comes closest to that here because the partner is treated in the same week as the index.\n\n### Whom partner services reaches\n\n\n::: {#tbl-yield .cell}\n\n```{.r .cell-code}\npn_scn <- c(\"pr\", \"pr_6mo\", \"ept\", \"ept_cur\")\nper_index <- function(s, x) sum(x) / sum(res[[s]]$index)\nyield_tbl <- data.frame(\n  Scenario = labels[pn_scn],\n  `Indices per year` = sapply(pn_scn, function(s)\n    round(mean(res[[s]]$index) / (horizon / 52))),\n  `Partners found per index` = sapply(pn_scn, function(s)\n    round(per_index(s, res[[s]]$found), 2)),\n  `Ongoing main, casual, ended (%)` = sapply(pn_scn, function(s) {\n    paste(round(100 * colSums(res[[s]]$found) / sum(res[[s]]$found)),\n          collapse = \", \")\n  }),\n  `Reached per index` = sapply(pn_scn, function(s)\n    round(per_index(s, res[[s]]$reach), 2)),\n  `Reached who are infected (%)` = sapply(pn_scn, function(s)\n    round(100 * sum(res[[s]]$reach_inf) / sum(res[[s]]$reach))),\n  `Infected by type: main, casual, ended (%)` = sapply(pn_scn, function(s) {\n    p <- 100 * colSums(res[[s]]$reach_inf) / colSums(res[[s]]$reach)\n    paste(ifelse(is.nan(p), \"-\", round(p)), collapse = \", \")\n  }),\n  `Partners diagnosed per index` = sapply(pn_scn, function(s)\n    round(per_index(s, res[[s]]$part_dx), 2)),\n  check.names = FALSE, row.names = NULL\n)\nknitr::kable(yield_tbl, caption = \"Indices handled per year (including partners diagnosed through patient referral), partners found in the lookback window per index (including partners already in care, who are not contacted) and their partnership type, partners reached per index, the share of reached partners who were infected overall and by partnership type, and partners diagnosed per index, pooled over simulations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Indices handled per year (including partners diagnosed through patient referral), partners found in the lookback window per index (including partners already in care, who are not contacted) and their partnership type, partners reached per index, the share of reached partners who were infected overall and by partnership type, and partners diagnosed per index, pooled over simulations\n\n|Scenario                   | Indices per year| Partners found per index|Ongoing main, casual, ended (%) | Reached per index| Reached who are infected (%)|Infected by type: main, casual, ended (%) | Partners diagnosed per index|\n|:--------------------------|----------------:|------------------------:|:-------------------------------|-----------------:|----------------------------:|:-----------------------------------------|----------------------------:|\n|Patient referral, 60 days  |              236|                     1.50|49, 27, 24                      |              0.35|                           71|78, 63, 46                                |                         0.25|\n|Patient referral, 6 months |              216|                     1.99|37, 19, 44                      |              0.40|                           67|78, 66, 36                                |                         0.26|\n|EPT, 60 days               |              151|                     1.44|48, 28, 25                      |              0.63|                           72|76, 65, 53                                |                         0.00|\n|EPT, ongoing partners only |              145|                     1.07|64, 36, 0                       |              0.57|                           76|77, 70, -                                 |                         0.00|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1), mar = c(4, 4.5, 3, 1), mgp = c(2.6, 0.8, 0))\nyield <- sapply(pn_scn, function(s) {\n  r <- res[[s]]\n  c(colSums(r$reach_inf), colSums(r$reach) - colSums(r$reach_inf)) / sum(r$index)\n})\nycols <- c(\"#8e44ad\", \"#e67e22\", \"#566573\", \"#d7bde2\", \"#f5cba7\", \"#d5d8dc\")\nbarplot(yield, names.arg = c(\"PR, 60 days\", \"PR, 6 months\", \"EPT, 60 days\",\n                             \"EPT, ongoing only\"),\n        col = ycols, cex.names = 0.85, ylab = \"Partners reached per index\",\n        main = \"Who Partner Services Reaches\",\n        ylim = c(0, max(colSums(yield)) * 1.45))\nlegend(\"top\", ncol = 3, bty = \"n\", fill = ycols[c(1, 4, 2, 5, 3, 6)], cex = 0.75,\n       legend = c(\"Main, infected\", \"Main, uninfected\", \"Casual, infected\",\n                  \"Casual, uninfected\", \"Ended, infected\", \"Ended, uninfected\"))\n```\n\n::: {.cell-output-display}\n![Partners reached per index, by partnership type and infection status when reached.](index_files/figure-html/fig-yield-1.png){#fig-yield width=768}\n:::\n:::\n\n\nPatient referral with a 60-day window finds 1.5 partners per index and reaches 0.35; the partners found but not contacted include those already in care, among them the index who referred a partner diagnosed at a PR visit. Index patients in UK clinics named 1.18 to 1.48 partners over a six-month window ([Public Health England 2016](https://assets.publishing.service.gov.uk/media/5b80052fed915d74f2d4c70b/NCSP_PN_audit_report_FINAL.pdf); Estcourt 2022), fewer than the 1.99 partners per index that the model finds over six months, as expected when not every partner is named. Of the partners found in 60 days, 24% are in partnerships that had already ended, the part of the program that only a partnership history can supply. The six-month window raises that share to 44%: the partners it adds are former partners, who are reached one time in ten and are less often infected. Most of the population effect of partner notification comes from ongoing partners here, as in other models ([Althaus et al. 2012](https://doi.org/10.1371/journal.pone.0051438); [Althaus et al. 2014](https://doi.org/10.3310/hta18020)) and with the small difference between one-month and six-month windows in [Weiss et al. 2019](https://doi.org/10.1097/OLQ.0000000000001058).\n\nEPT reaches 0.63 partners per index, 0.28 more than patient referral (the Cochrane review found 0.43 more partners treated per index), and it gives up the 0.25 partners per index who are diagnosed under patient referral and become indices themselves. In a Scottish audit, testing partners and tracing their partners in turn found 22% to 28% more infections than treating partners without testing would have ([Forbes and Clutterbuck 2009](https://doi.org/10.1258/ijsa.2008.008387)). Between 67% and 76% of the partners reached are infected, depending on the program, at the top of the published range for current partners and well above the 34% of all notified partners who tested positive in Dutch clinics ([van Aar et al. 2018](https://doi.org/10.1136/sextrans-2017-053364)), because the partners reached here are mostly ongoing partners of long standing. Under EPT, 28% of treatments go to uninfected partners, fewer than the 52% to 63% in the EpiModel study of EPT among men who have sex with men (Weiss 2019), for the same reason.\n\n### Between-simulation variability\n\n\n::: {#tbl-cv .cell}\n\n```{.r .cell-code}\ncv_tbl <- data.frame(\n  Scenario = labels[names(res)],\n  `Mean prevalence after 5 years (%)` = sapply(res, function(r) round(mean(r$prev), 1)),\n  `Range across simulations (%)` = sapply(res, function(r)\n    sprintf(\"%.1f to %.1f\", min(r$prev), max(r$prev))),\n  `CV of five-year infections` = sapply(res, function(r)\n    round(sd(r$inf) / mean(r$inf), 2)),\n  check.names = FALSE, row.names = NULL\n)\nknitr::kable(cv_tbl, caption = \"Prevalence in the fifth scenario year (mean and range across simulations) and the coefficient of variation of five-year infections, by scenario\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Prevalence in the fifth scenario year (mean and range across simulations) and the coefficient of variation of five-year infections, by scenario\n\n|Scenario                   | Mean prevalence after 5 years (%)|Range across simulations (%) | CV of five-year infections|\n|:--------------------------|---------------------------------:|:----------------------------|--------------------------:|\n|No partner services        |                               6.3|2.9 to 8.6                   |                       0.29|\n|Patient referral, 60 days  |                               3.7|1.5 to 5.1                   |                       0.28|\n|Patient referral, 6 months |                               3.0|0.8 to 4.6                   |                       0.37|\n|EPT, 60 days               |                               2.6|1.8 to 3.7                   |                       0.28|\n|EPT, ongoing partners only |                               2.5|1.7 to 4.2                   |                       0.34|\n\n\n:::\n:::\n\n\nBetween-simulation variation is large. Endemic prevalence in a population of 10,000 with a small core group wanders from one simulation to the next, so prevalence five years after the change ranges from 1.5 to 5.1% under patient referral, with a coefficient of variation of five-year infections near 0.28. Resuming a shared burn-in removes the variation that the scenarios share at the moment they resume, but not the divergence that follows, which is why the intervals on infections averted are wide. More simulations narrow the intervals in proportion to the square root of their number, and the run time grows in proportion to the number.\n\n### Summary\n\nIn this model, patient referral at the level of US practice keeps a chlamydia-like infection endemic at about 3% to 4% prevalence, and removing it raises new infections by 39.9% within five years. EPT lowers infections by a further 16.4% (60-day window) and 20.4% (ongoing partners only) and lowers repeat infection of cured cases by about 30% relative to patient referral, despite ending the chain of diagnosis, because it reaches more partners and reaches them sooner. A six-month lookback finds many more partners, mostly former ones, and lowers infections by 10.8%, with an interval that includes zero. Nearly every repeat infection comes from a partner the person already had when cured, which is the failure partner notification exists to prevent.\n\n## Next Steps\n\n- **Abstinence until partners are treated.** In `infect`, drop the discordant pairs in which one partner is a cured index still within an abstinence window and the other is an ongoing partner who has not been treated. In the Golden trial, 88% of women with chlamydia reported no sex with an untreated partner; the change should bring repeat infection toward the observed range and shows how much of partner notification's benefit survives a realistic behavioral response.\n- **Offer EPT and fall back to PR.** Draw each index's acceptance of EPT (a median of 65% in Layton 2020) and send the partners of indices who decline down the PR path. This is how EPT is delivered, and it turns the EPT scenarios from upper bounds into estimates.\n- **The most recent partner.** CDC guidance also notifies the most recent partner when the last partnership ended before the 60-day window. Call `get_partners()` with a longer `truncate` (and raise `truncate.el.cuml` to match), keep, for each index with no partner in the window, the row with the latest `stop`, and treat that partner.\n- **Retesting at three months.** Schedule a test at `tx.time + 13` for a share of cured cases. Repeat infections are then found and treated, and each one starts a new round of partner notification.\n- **Test before treating.** Treat reached partners only if they test positive, as the 2026 BASHH guideline does for late-presenting asymptomatic contacts, and count the treatments saved against the infections missed.\n- **Age structure and asymmetric transmission.** Add age groups with age-disparate mixing and a higher male-to-female transmission probability. Both should raise prevalence in young women relative to young men toward the NHANES pattern.\n- **Costs.** The partners treated and infections averted here are the inputs of a cost-effectiveness analysis; the [cost-effectiveness example](../cost-effectiveness/) shows how to attach costs and quality-adjusted life years to an EpiModel simulation.\n\n## References\n\nPartner notification guidance, trials, and program data:\n\n- Workowski KA, Bachmann LH, Chan PA, et al. (2021). Sexually transmitted infections treatment guidelines, 2021. *MMWR Recomm Rep* 70(4):1-187. <https://doi.org/10.15585/mmwr.rr7004a1>\n- Centers for Disease Control and Prevention. (2006). Expedited partner therapy in the management of sexually transmitted diseases: review and guidance. <https://stacks.cdc.gov/view/cdc/6804>\n- McClean H, Radcliffe K, Sullivan A, Ahmed-Jushuf I. (2013). 2012 BASHH statement on partner notification for sexually transmissible infections. *Int J STD AIDS* 24(4):253-261. <https://doi.org/10.1177/0956462412472804>\n- Saunders J, Burley N, Brice S, et al. (2026). British Association for Sexual Health and HIV UK national guideline for the management of infection with *Chlamydia trachomatis*, 2026. *Int J STD AIDS*, published online August 24, 2026. <https://doi.org/10.1177/09564624261475950>\n- Schillinger JA, Kissinger P, Calvet H, et al. (2003). Patient-delivered partner treatment with azithromycin to prevent repeated *Chlamydia trachomatis* infection among women: a randomized, controlled trial. *Sex Transm Dis* 30(1):49-56. <https://doi.org/10.1097/00007435-200301000-00011>\n- Golden MR, Whittington WLH, Handsfield HH, et al. (2005). Effect of expedited treatment of sex partners on recurrent or persistent gonorrhea or chlamydial infection. *N Engl J Med* 352(7):676-685. <https://doi.org/10.1056/NEJMoa041681>\n- Kissinger P, Mohammed H, Richardson-Alston G, et al. (2005). Patient-delivered partner treatment for male urethritis: a randomized, controlled trial. *Clin Infect Dis* 41(5):623-629. <https://doi.org/10.1086/432476>\n- Ferreira A, Young T, Mathews C, Zunza M, Low N. (2013). Strategies for partner notification for sexually transmitted infections, including HIV. *Cochrane Database Syst Rev* (10):CD002843. <https://doi.org/10.1002/14651858.CD002843.pub2>\n- Estcourt CS, Stirrup O, Copas A, et al. (2022). Accelerated partner therapy contact tracing for people with chlamydia (LUSTRUM): a crossover cluster-randomised controlled trial. *Lancet Public Health* 7(10):e853-e865. <https://doi.org/10.1016/S2468-2667(22)00204-3>\n- Golden MR, Kerani RP, Stenger M, et al. (2015). Uptake and population-level impact of expedited partner therapy (EPT) on *Chlamydia trachomatis* and *Neisseria gonorrhoeae*: the Washington State community-level randomized trial of EPT. *PLoS Med* 12(1):e1001777. <https://doi.org/10.1371/journal.pmed.1001777>\n- Public Health England. (2016). Partner notification in chlamydia screening: national audit report. <https://assets.publishing.service.gov.uk/media/5b80052fed915d74f2d4c70b/NCSP_PN_audit_report_FINAL.pdf>\n- Estcourt CS, Flowers P, Cassell JA, et al. (2022). Going beyond 'regular and casual': development of a classification of sexual partner types to enhance partner notification for STIs. *Sex Transm Infect* 98(2):108-114. <https://doi.org/10.1136/sextrans-2020-054846>\n- Layton E, Vaisey A, Goller JL, et al. (2020). The views of patients and partners toward patient-delivered partner therapy for chlamydia: a systematic review. *Sex Transm Dis* 47(12):790-797. <https://doi.org/10.1097/OLQ.0000000000001260>\n- Golden MR, Hogben M, Handsfield HH, et al. (2003). Partner notification for HIV and STD in the United States: low coverage for gonorrhea, chlamydial infection, and HIV. *Sex Transm Dis* 30(6):490-496. <https://doi.org/10.1097/00007435-200306000-00004>\n- Patel HC, Viswalingam ND, Goh BT. (1994). Chlamydial ocular infection: efficacy of partner notification by patient referral. *Int J STD AIDS* 5(4):244-247. <https://doi.org/10.1177/095646249400500403>\n- McMahon BL, Buitendam E, Symonds M, Estcourt CS, Saunders J. (2025). Use of a five-category partner-type classification within a chlamydia and gonorrhoea service evaluation highlights opportunities for targeted partner notification to improve STI control. *Sex Transm Infect* 101(1):55-58. <https://doi.org/10.1136/sextrans-2024-056108>\n- Forbes G, Clutterbuck DJ. (2009). How many cases of chlamydial infection would we miss by not testing partners for infection? *Int J STD AIDS* 20(4):267-268. <https://doi.org/10.1258/ijsa.2008.008387>\n- van Aar F, van Benthem BHB, van den Broek IVF, Götz HM. (2018). STIs in sex partners notified for chlamydia exposure: implications for expedited partner therapy. *Sex Transm Infect* 94(8):619-621. <https://doi.org/10.1136/sextrans-2017-053364>\n\nModels of chlamydia and partner notification:\n\n- Yorke JA, Hethcote HW, Nold A. (1978). Dynamics and control of the transmission of gonorrhea. *Sex Transm Dis* 5(2):51-56. <https://doi.org/10.1097/00007435-197804000-00003>\n- Kretzschmar M, van Duynhoven YT, Severijnen AJ. (1996). Modeling prevention strategies for gonorrhea and *Chlamydia* using stochastic network simulations. *Am J Epidemiol* 144(3):306-317. <https://doi.org/10.1093/oxfordjournals.aje.a008926>\n- Turner KME, Adams EJ, Gay N, Ghani AC, Mercer C, Edmunds WJ. (2006). Developing a realistic sexual network model of chlamydia transmission in Britain. *Theor Biol Med Model* 3:3. <https://doi.org/10.1186/1742-4682-3-3>\n- Althaus CL, Heijne JCM, Roellin A, Low N. (2010). Transmission dynamics of *Chlamydia trachomatis* affect the impact of screening programmes. *Epidemics* 2(3):123-131. <https://doi.org/10.1016/j.epidem.2010.04.002>\n- Heijne JCM, Althaus CL, Herzog SA, Kretzschmar M, Low N. (2011). The role of reinfection and partner notification in the efficacy of *Chlamydia* screening programs. *J Infect Dis* 203(3):372-377. <https://doi.org/10.1093/infdis/jiq050>\n- Althaus CL, Heijne JCM, Herzog SA, Roellin A, Low N. (2012). Individual and population level effects of partner notification for *Chlamydia trachomatis*. *PLoS One* 7(12):e51438. <https://doi.org/10.1371/journal.pone.0051438>\n- Kretzschmar M, Satterwhite C, Leichliter J, Berman S. (2012). Effects of screening and partner notification on *Chlamydia* positivity in the United States: a modeling study. *Sex Transm Dis* 39(5):325-331. <https://doi.org/10.1097/OLQ.0b013e31824e52c2>\n- Althaus CL, Turner KME, Mercer CH, et al. (2014). Effectiveness and cost-effectiveness of traditional and new partner notification technologies for curable sexually transmitted infections: observational study, systematic reviews and mathematical modelling. *Health Technol Assess* 18(2):1-100. <https://doi.org/10.3310/hta18020>\n- Low N, Heijne JCM, Herzog SA, Althaus CL. (2014). Reinfection by untreated partners of people treated for *Chlamydia trachomatis* and *Neisseria gonorrhoeae*: mathematical modelling study. *Sex Transm Infect* 90(3):254-256. <https://doi.org/10.1136/sextrans-2013-051279>\n- Weiss KM, Jones JS, Katz DA, et al. (2019). Epidemiological impact of expedited partner therapy for men who have sex with men: a modeling study. *Sex Transm Dis* 46(11):697-705. <https://doi.org/10.1097/OLQ.0000000000001058>\n- Kao SZ, Enns EA. (2020). Follow the sex: influence of network structure on the effectiveness and cost-effectiveness of partner management strategies for sexually transmitted infection control. *Sex Transm Dis* 47(2):71-79. <https://doi.org/10.1097/OLQ.0000000000001100>\n\nNatural history, transmission, and epidemiology:\n\n- Lewis J, Price MJ, Horner PJ, White PJ. (2017). Genital *Chlamydia trachomatis* infections clear more slowly in men than women, but are less likely to become established. *J Infect Dis* 216(2):237-244. <https://doi.org/10.1093/infdis/jix283>\n- Davies B, Anderson SJ, Turner KME, Ward H. (2014). How robust are the natural history parameters used in chlamydia transmission dynamic models? A systematic review. *Theor Biol Med Model* 11:8. <https://doi.org/10.1186/1742-4682-11-8>\n- Farley TA, Cohen DA, Elkins W. (2003). Asymptomatic sexually transmitted diseases: the case for screening. *Prev Med* 36(4):502-509. <https://doi.org/10.1016/s0091-7435(02)00058-0>\n- Quinn TC, Gaydos C, Shepherd M, et al. (1996). Epidemiologic and microbiologic correlates of *Chlamydia trachomatis* infection in sexual partnerships. *JAMA* 276(21):1737-1742. PMID 8940322.\n- Althaus CL, Heijne JCM, Low N. (2012). Towards more robust estimates of the transmissibility of *Chlamydia trachomatis*. *Sex Transm Dis* 39(5):402-404. <https://doi.org/10.1097/OLQ.0b013e318248a550>\n- Lewis J, White PJ, Price MJ. (2021). Per-partnership transmission probabilities for *Chlamydia trachomatis* infection: evidence synthesis of population-based survey data. *Int J Epidemiol* 50(2):510-517. <https://doi.org/10.1093/ije/dyaa202>\n- Rogers SM, Miller WC, Turner CF, et al. (2008). Concordance of *Chlamydia trachomatis* infections within sexual partnerships. *Sex Transm Infect* 84(1):23-28. <https://doi.org/10.1136/sti.2007.027029>\n- Torrone E, Papp J, Weinstock H. (2014). Prevalence of *Chlamydia trachomatis* genital infection among persons aged 14-39 years, United States, 2007-2012. *MMWR Morb Mortal Wkly Rep* 63(38):834-838. PMID 25254560.\n- Kreisel KM, Weston EJ, St Cyr SB, Spicknall IH. (2021). Estimates of the prevalence and incidence of chlamydia and gonorrhea among US men and women, 2018. *Sex Transm Dis* 48(4):222-231. <https://doi.org/10.1097/OLQ.0000000000001382>\n- Centers for Disease Control and Prevention. (2024). Sexually transmitted infections surveillance, 2023. <https://stacks.cdc.gov/view/cdc/255132>\n- Pazol K, Robbins CL, Black LI, et al. (2017). Receipt of selected preventive health services for women and men of reproductive age, United States, 2011-2013. *MMWR Surveill Summ* 66(20):1-31. <https://doi.org/10.15585/mmwr.ss6620a1>\n- He L, Patel C, Tao G. (2023). National chlamydia screening rate in young sexually active women using HEDIS measures in the United States, 2011 to 2020. *Sex Transm Dis* 50(7):415-419. <https://doi.org/10.1097/OLQ.0000000000001809>\n- Geisler WM, Uniyal A, Lee JY, et al. (2015). Azithromycin versus doxycycline for urogenital *Chlamydia trachomatis* infection. *N Engl J Med* 373(26):2512-2521. <https://doi.org/10.1056/NEJMoa1502599>\n- Kong FYS, Tabrizi SN, Law M, et al. (2014). Azithromycin versus doxycycline for the treatment of genital chlamydia infection: a meta-analysis of randomized controlled trials. *Clin Infect Dis* 59(2):193-205. <https://doi.org/10.1093/cid/ciu220>\n- Hosenfeld CB, Workowski KA, Berman S, et al. (2009). Repeat infection with chlamydia and gonorrhea among females: a systematic review of the literature. *Sex Transm Dis* 36(8):478-489. <https://doi.org/10.1097/OLQ.0b013e3181a2a933>\n- Fung M, Scott KC, Kent CK, Klausner JD. (2007). Chlamydial and gonococcal reinfection among men: a systematic review of data to evaluate the need for retesting. *Sex Transm Infect* 83(4):304-309. <https://doi.org/10.1136/sti.2006.024059>\n- Mercer CH, Tanton C, Prah P, et al. (2013). Changes in sexual attitudes and lifestyles in Britain through the life course and over time: findings from the National Surveys of Sexual Attitudes and Lifestyles (Natsal). *Lancet* 382(9907):1781-1794. <https://doi.org/10.1016/S0140-6736(13)62035-8>\n- Chandra A, Mosher WD, Copen C, Sionean C. (2011). Sexual behavior, sexual attraction, and sexual identity in the United States: data from the 2006-2008 National Survey of Family Growth. *Natl Health Stat Report* (36):1-36. <https://www.cdc.gov/nchs/data/nhsr/nhsr036.pdf>\n- Burington B, Hughes JP, Whittington WLH, et al. (2010). Estimating duration in partnership studies: issues, methods and examples. *Sex Transm Infect* 86(2):84-89. <https://doi.org/10.1136/sti.2009.037960>\n\nThe network structure, transmission probability, testing rates, and reach probabilities are illustrative choices, selected to place the model in a plausible endemic regime for young heterosexual adults and to reproduce the published targets in the calibration table. They are not calibrated to any population.\n\n## Author\n\n[Samuel M. Jenness](http://samueljenness.org/), Emory University\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}