{
  "hash": "e87fd48108b4d07414c41f9ddfd103dd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Age-Stratified RSV on a Household + Community Network\"\ndescription: \"A respiratory virus example: a population built from households (each a fixed clique) plus a TERGM community layer with a fully specified age-mixing matrix, age-based prior immunity, recorded transmission chains, and age-targeted products (older-adult vaccine, infant antibody) with separate infection-blocking and severity-reducing effects, compared with household cocooning, an equal-dose random comparator, and an NPI.\"\nauthor: \"Samuel M. Jenness\"\ndate: \"2026-09-20\"\ncategories: [RSV, SEIR, multilayer, households, age structure, vaccination, advanced]\norder: 11\nimage: thumbnail.png\n---\n\n## Overview\n\nRespiratory syncytial virus (RSV) is a respiratory virus that spreads through everyday close contact rather than through the long-duration partnerships that most Gallery examples model. Nearly everyone is infected by age 2 and reinfected throughout life, so susceptibility and severity are strongly age-dependent: severe disease concentrates in infants and older adults, while children carry most transmission. Since 2023 there has been a portfolio of age-targeted products (long-acting monoclonal antibodies for infants, maternal vaccination, and vaccines for older adults), and public health agencies use scenario models to ask which products avert the most hospitalizations.\n\nThis example builds a single-season RSV model with three features that no other Gallery example combines:\n\n1. **A household plus community network.** The population is generated household by household, and every household is a fixed clique: a static contact layer that is not an ERGM and is never resimulated. On top of it runs a *community* layer, a TERGM of transient daily contacts in which every cell of the age-by-age mixing matrix is set through `nodemix`. The example shows how to combine a hand-built static layer with a simulated dynamic one inside `netsim`, and how to record every transmission with its layer so that who-infects-whom can be analyzed afterwards.\n\n2. **A five-stratum age structure that governs contact, susceptibility, severity, and eligibility.** Infants (< 1 year), young children (1-4), school-age children (5-17), adults (18-64), and older adults (65+). Age is used as a proxy for prior exposure history, so older groups are less susceptible per contact.\n\n3. **Age-targeted and household-targeted interventions.** The older-adult vaccine and the infant monoclonal antibody each reduce the per-contact probability of infection (which also protects others) and the risk of hospitalization given infection (which protects only the recipient). Because households are explicit, a *cocooning* scenario that immunizes the co-residents of infants is definable, and an equal-dose comparator that immunizes people of the same ages chosen at random shows what the household link itself contributes. A community-layer non-pharmaceutical intervention (NPI) is included as a comparison.\n\nThe policy question is the one asked of RSV scenario models: *in one season, which strategy averts the most hospitalizations, how many doses does each hospitalization averted cost, and how much of each product's effect is indirect?* The example also shows how to answer it honestly on a stochastic network model, with Monte Carlo intervals on every intervention effect.\n\n::: {.callout-note}\n## How this relates to other RSV scenario tools\n\nThe [RSV Scenario Modeling Hub](https://rsvscenariomodelinghub.org/) and the [R.Scenario.Vax](https://chelsea-hansen.github.io/R.Scenario.Vax/) package use age-structured compartmental models that are calibrated to [RSV-NET](https://www.cdc.gov/rsv/php/surveillance/rsv-net.html) hospitalizations and include births, maternal immunity, exposure-history immunity, seasonal forcing, and waning of product protection across seasons. Those tools are built to project hospitalizations for a specific place and season. This example trades those features for an explicit contact network, so that transmission within households can be separated from transmission in the community and interventions can be targeted at the individual or household level. It follows the Hub's convention of stating product effectiveness against hospitalization, but its parameters are illustrative and it is not calibrated to surveillance data. Treat it as a template for building an RSV network model, not as a forecasting tool.\n:::\n\n::: {.callout-tip}\n## Download and run the standalone scripts\n\n- [model.R](model.R): main simulation script\n- [module-fx.R](module-fx.R): custom module functions\n\n`model.R` sources `module-fx.R` from `examples/rsv/` when run from the repository root and from the working directory otherwise, so the two downloaded files can sit in one folder. Sourcing the script interactively (for example in RStudio) uses the full settings on this page (`N = 10000`, ten simulations, 150 days, two to three minutes on a laptop). `Rscript` is not interactive and uses the small continuous-integration settings (`N = 1000`, one simulation, 50 days, well under a minute) whose results are not meant to be interpreted; to get the full settings from the command line, pass R code that defines `run_full` as the first argument:\n\n```bash\nRscript model.R \"run_full <- TRUE\"\n```\n:::\n\n## Model Structure\n\n### Disease Compartments\n\n| Status | Sub-stage | Description |\n|---|---|---|\n| **S** | | Susceptible (per-contact susceptibility scaled by age) |\n| **E** | | Exposed, latent (mean 4 days) |\n| **I** | `inf_stage = \"ip\"` | Presymptomatic infectious (mean 2 days), for infections that will become symptomatic |\n| **I** | `inf_stage = \"is\"` | Symptomatic infectious (mean 7 days) |\n| **I** | `inf_stage = \"ia\"` | Asymptomatic infectious (mean 7 days, half as infectious); these infections skip the presymptomatic stage |\n| **R** | | Recovered, immune for the rest of the season |\n\nThe standard `status` attribute holds the SEIR compartment and an additional `inf_stage` attribute carries the I substage. Whether an infection will be symptomatic is decided when it leaves E: 70% enter the presymptomatic stage and then become symptomatic, and 30% are asymptomatic throughout. Every stage duration is geometric with the stated mean, because each transition is a daily Bernoulli draw. The presymptomatic and asymptomatic stages are what make NPIs relevant for respiratory pathogens: isolation triggered by symptoms misses both.\n\n```{mermaid}\n%%| echo: false\nflowchart LR\n    S[\"<b>S</b>\"] -->|\"infection<br/>(household or community)\"| E\n    E[\"<b>E</b>\"] -->|\"~4 days, 70%\"| Ip\n    E -->|\"~4 days, 30%\"| Ia[\"<b>I_a</b><br/>asymp\"]\n    Ip[\"<b>I_p</b><br/>presymp\"] -->|\"~2 days\"| Is[\"<b>I_s</b><br/>symp\"]\n    Is -->|\"~7 days\"| R[\"<b>R</b>\"]\n    Ia -->|\"~7 days\"| R\n\n    style S fill:#3498db,color:#fff\n    style E fill:#9b59b6,color:#fff\n    style Ip fill:#f39c12,color:#fff\n    style Is fill:#e74c3c,color:#fff\n    style Ia fill:#e67e22,color:#fff\n    style R fill:#27ae60,color:#fff\n```\n\n### Age Structure\n\nEach age group differs in four ways: its household and community contact rates, its per-contact susceptibility (a proxy for prior immunity), its hospitalization risk per infection, and its eligibility for a product. The contact degrees below are realized values at N = 10,000: the household degree follows from the household mix, and the community degree from the fitted ERGM (see the diagnostics sections).\n\n| Group | Ages | Share of N | Household degree | Community degree | Susceptibility (`sus.mult`) | Hospitalization risk per infection | Product |\n|---|---|---|---|---|---|---|---|\n| infant | < 1 | 1.2% | 2.8 | 2.3 | 1.00 | 0.030 | monoclonal antibody |\n| young | 1-4 | 5.2% | 2.6 | 5.3 | 0.55 | 0.006 | |\n| school | 5-17 | 18% | 2.7 | 6.9 | 0.16 | 0.001 | |\n| adult | 18-64 | 58% | 1.8 | 5.0 | 0.07 | 0.004 | |\n| elderly | 65+ | 18% | 0.9 | 3.1 | 0.13 | 0.045 | vaccine |\n\nAnyone other than an infant who lives with an infant is eligible for the hypothetical cocooning product.\n\nHospitalization is not a compartment. Expected hospitalizations are computed after the simulation as infections times the per-infection risk, with the risk further reduced for immunized people. This keeps the disease model simple while letting the analysis report the burden-weighted outcome that RSV policy is judged on.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages(library(EpiModel))\n\n# These are the full settings of the standalone model.R. The population is\n# larger than in other Gallery examples because the outcome strata at the\n# age extremes are small: infants are about 1% of N.\nN <- 10000\nnsims <- 10\nncores <- 5\nnsteps <- 150\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The custom modules (init_attrs, infect, progress) used in control.net().\n# The excerpts shown under \"Custom Modules\" are pulled from this file.\nsource(\"module-fx.R\")\n```\n:::\n\n\n## Population and Households\n\nThe population is built from households rather than from individuals. Each entry in `hh_types` is a household type: the name lists its members by age group and the value is the probability that a sampled household is of that type. This is the simplest way to get a joint distribution of ages *within* households, which is what the household layer needs: every infant lives with at least one adult, about 60% of infants have an older sibling (in the United States about 60% of births are second or later births), about 10% of infants live with a single adult, some infants have a co-resident grandparent, and about 28% of older adults live alone. The mix was chosen so that the person-level age shares approximate the United States, with a mean household size of 2.3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhh_types <- c(\n  \"adult\"                          = 0.150,\n  \"adult adult\"                    = 0.182,\n  \"adult adult adult\"              = 0.050,\n  \"elderly\"                        = 0.120,\n  \"elderly elderly\"                = 0.120,\n  \"adult elderly\"                  = 0.030,\n  \"adult adult infant\"             = 0.007,\n  \"adult adult infant young\"       = 0.007,\n  \"adult adult infant school\"      = 0.006,\n  \"adult adult infant young school\" = 0.003,\n  \"adult adult infant elderly\"     = 0.002,\n  \"adult infant\"                   = 0.002,\n  \"adult infant young\"             = 0.001,\n  \"adult adult young\"              = 0.030,\n  \"adult adult young young\"        = 0.010,\n  \"adult adult young school\"       = 0.035,\n  \"adult young\"                    = 0.010,\n  \"adult adult school\"             = 0.060,\n  \"adult adult school school\"      = 0.070,\n  \"adult adult school school school\" = 0.020,\n  \"adult school\"                   = 0.035,\n  \"adult school school\"            = 0.020,\n  \"adult adult school elderly\"     = 0.020,\n  \"adult adult young elderly\"      = 0.010\n)\nstopifnot(abs(sum(hh_types) - 1) < 1e-8)\n```\n:::\n\n\n### From household types to a static clique layer\n\nTwo helpers do the work. The first samples households until the population reaches `N` and returns each person's age group and household id, with households on consecutive node ids. The second turns the household ids into an edgelist by connecting every pair of co-residents, so each household is a clique. That edgelist *is* the household layer: there is no ERGM to fit and nothing to resimulate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_households <- function(N, hh_types, seed = NULL) {\n  if (!is.null(seed)) set.seed(seed)\n  members <- strsplit(names(hh_types), \" \")\n  sizes <- lengths(members)\n  n_draw <- ceiling(1.5 * N / sum(hh_types * sizes)) + 10\n  draw <- sample.int(length(hh_types), n_draw, replace = TRUE, prob = hh_types)\n  draw <- draw[seq_len(which(cumsum(sizes[draw]) >= N)[1])]           # <1>\n  age <- unlist(members[draw])[1:N]\n  hh_id <- rep(seq_along(draw), sizes[draw])[1:N]\n  list(age = age, hh_id = hh_id)\n}\n\nhousehold_edgelist <- function(hh_id) {\n  members <- split(seq_along(hh_id), hh_id)\n  members <- members[lengths(members) > 1]                              # <2>\n  el <- do.call(rbind, lapply(members, function(m) t(combn(m, 2))))\n  unname(el)\n}\n\npop <- generate_households(N, hh_types, seed = 123)\nage <- pop$age\nhh_id <- pop$hh_id\nhh_el <- household_edgelist(hh_id)\n\ncounts <- table(factor(age, levels = c(\"adult\", \"elderly\", \"infant\",\n                                       \"school\", \"young\")))\ncounts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  adult elderly  infant  school   young \n   5799    1812     117    1756     516 \n```\n\n\n:::\n:::\n\n1. Households are sampled until their cumulative size reaches `N`; at most the last household is cut short by the truncation to `N`.\n2. Single-person households contribute no edges. They still exist as nodes with a household id, and their only contacts are in the community layer.\n\n### Household-layer diagnostics\n\nBecause the layer is a fixed edgelist, its diagnostics are direct: the household size distribution and the mean degree by age are read from the data rather than from simulated networks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(tabulate(hh_id))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5 \n1157 1660  728  706  103 \n```\n\n\n:::\n\n```{.r .cell-code}\nhh_deg <- tabulate(c(hh_el[, 1], hh_el[, 2]), nbins = N)\ndeg_hh_by_age <- round(tapply(hh_deg, age, mean), 2)\ndeg_hh_by_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  adult elderly  infant  school   young \n   1.76    0.85    2.76    2.74    2.61 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note}\n## Why a clique layer rather than a long-duration ERGM\n\nAn earlier version of this example modeled family contacts as a second TERGM layer with a long mean tie duration. That gives the right *degree* by age but not the right *structure*: the ties form a sparse random graph over the whole population, so an infected adult's family ties reach into many different families, and an infant's two \"parents\" are unlikely to be each other's partners. Real household transmission is closed: the people an infant can infect at home are exactly the people who can infect it. A clique layer has that closure by construction, which is why household secondary attack rates, sibling-to-infant introduction, and household-targeted strategies (cocooning) can only be represented this way. The cost is that the layer has no dynamics and no ERGM; in a model with births or migration, arrivals have to be wired into an existing household by hand.\n:::\n\n## The Community Layer with `nodemix`\n\nThe community layer is a TERGM of transient daily contacts. Its formation model is `~edges + nodemix(\"age\")`, which gives every cell of the age-by-age mixing matrix its own target statistic. Both `age` and `hh_id` are set as vertex attributes so that `netsim` carries them into the simulation, where the modules read them with `get_attr()`.\n\n### Why every cell is targeted\n\n`nodemix` lets you target any subset of the mixing cells. It is tempting to constrain only the cells that carry epidemiological signal and leave the others free. The catch is what \"free\" means: the untargeted cells share the baseline `edges` coefficient, so whatever edge count remains after the targeted cells are filled is spread across the untargeted dyads at a uniform per-dyad rate. Because the adult-by-elderly block contains far more dyads than any other cross-age block, a sparse specification quietly gives older adults among the highest degrees in the layer, and infants a community degree several times what was intended. Targeting the full matrix fixes the degree of every age group by design, and the diagnostics below verify it.\n\nThe cell ordering ergm uses for `nodemix` is the upper triangle of the mixing matrix, column-major, with alphabetical levels. Rather than hard-coding the 15 cell names, we read them from ergm:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnw <- network_initialize(N)\nnw <- set_vertex_attribute(nw, \"age\", age)\nnw <- set_vertex_attribute(nw, \"hh_id\", hh_id)\n\ncells <- sub(\"^mix\\\\.age\\\\.\", \"\",\n             names(summary(nw ~ nodemix(\"age\", levels2 = TRUE))))\ncells\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"adult.adult\"     \"adult.elderly\"   \"elderly.elderly\" \"adult.infant\"   \n [5] \"elderly.infant\"  \"infant.infant\"   \"adult.school\"    \"elderly.school\" \n [9] \"infant.school\"   \"school.school\"   \"adult.young\"     \"elderly.young\"  \n[13] \"infant.young\"    \"school.young\"    \"young.young\"    \n```\n\n\n:::\n:::\n\n\n### From a contact profile to cell targets\n\nContact rates are easier to think about per person than per cell, so the layer is specified as a *profile*: each entry `a.b` is the mean number of `b`-partners per `a`-node. The helper multiplies by the size of group `a` (halving within-group cells, where each edge is counted from both ends), maps the pair to its canonical cell name, and rounds to whole edges so that ergm can match the targets exactly. Cross-age entries are written from the perspective of the smaller group because that is the number with an intuitive meaning (each school-age child has 1.5 adult community contacts; each adult has 0.5 school-age contacts).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmix_targets <- function(profile, counts, cells) {\n  out <- setNames(numeric(length(cells)), cells)\n  for (nm in names(profile)) {\n    ab <- strsplit(nm, \".\", fixed = TRUE)[[1]]\n    n_a <- as.numeric(counts[ab[1]])\n    e <- if (ab[1] == ab[2]) n_a * profile[[nm]] / 2 else n_a * profile[[nm]]\n    cell <- paste(sort(ab), collapse = \".\")\n    stopifnot(cell %in% cells)\n    out[cell] <- out[cell] + e\n  }\n  pmax(round(out), 1)\n}\n```\n:::\n\n\nDaily contacts outside the household, with the strong age assortativity seen in contact surveys ([Mossong et al. 2008](https://doi.org/10.1371/journal.pmed.0050074)). School-age children have the highest degree and mix mostly with each other; this is the model's school amplifier. Infants have the fewest community contacts: non-household caregivers and, for the share of infants in child care, other infants and young children.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncom_profile <- c(\n  school.school   = 5.0,   # classmates                               # <1>\n  adult.adult     = 4.0,   # workplace, social\n  young.young     = 2.5,   # child care\n  elderly.elderly = 1.5,\n  school.adult    = 1.5,   # teachers, coaches, friends' parents\n  young.adult     = 2.0,   # child care staff\n  elderly.adult   = 1.2,\n  school.elderly  = 0.3,   # grandparents\n  young.school    = 0.5,\n  infant.adult    = 1.0,   # non-household caregivers\n  infant.young    = 0.6,   # child care                                # <2>\n  infant.infant   = 0.3,   # child care\n  infant.school   = 0.2,\n  infant.elderly  = 0.2,\n  young.elderly   = 0.3\n)\ncom_targets <- mix_targets(com_profile, counts, cells)\n```\n:::\n\n1. The magnitude of within-school contact is a model choice, not a calibrated estimate. Changing it is the quickest way to see how much the school amplifier drives infections in the other age groups.\n2. The infant entries were raised, relative to an earlier version, until the baseline infant attack rate landed in the published range (see the parameter table below). Whether an infant's exposure comes mostly from home or from child care is a setting-specific question, and the transmission matrix reported in the analysis shows what these values imply.\n\n::: {.callout-warning}\n## Two simplifications in the community layer\n\n**Contacts do not persist.** Every community tie lasts one day, so classmates and coworkers are redrawn daily. The layer reproduces the daily contact *rate* by age but not the persistence of real school and workplace contacts. This is the simplest TERGM specification and a consequential one: a longer tie duration at the same mean degree would make repeated contacts with the same infectious person more likely and spread infection through fewer households. Varying `duration` in `dissolution_coefs()` while holding the profile fixed is a worthwhile experiment (see Next Steps).\n\n**Co-residents can also meet in the community.** The ERGM does not exclude household pairs from the community layer. The expected number of community edges that fall on a household pair is the number of household pairs times the per-dyad tie probability, which is a few edges per day among the roughly 25,000 in the layer, and those pairs already transmit at the higher household rate. Excluding them would need an ergm constraint on the household dyads and was not worth the complexity here.\n:::\n\n### Fitting the community layer\n\n`levels2 = -1` drops the first cell (adult.adult) as the reference; its count is implied by the `edges` target minus the other 14 cells. Community ties last one day.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformation <- ~edges + nodemix(\"age\", levels2 = -1)\n\nsan_ctrl <- control.ergm(SAN = control.san(SAN.maxit = 20,          # <1>\n                                           SAN.nsteps = 2^21))\n\ncoef.diss_com <- dissolution_coefs(~offset(edges), duration = 1)\n\nest_com <- netest(nw, formation,\n                  target.stats = c(sum(com_targets),\n                                   as.numeric(com_targets[-1])),\n                  coef.diss = coef.diss_com,\n                  set.control.ergm = san_ctrl, verbose = FALSE)\n```\n:::\n\n1. **SAN budget.** With 14 targeted cells, ergm's default simulated annealing step sometimes cannot hit every target exactly, and ergm then falls back to MCMC estimation, which takes minutes for a model that is dyad-independent and could be fit by maximum pseudolikelihood in seconds. Giving SAN more iterations and steps lets it match the targets, after which the fast fit is used.\n\n### Community-layer diagnostics\n\nThe check that the profile translated into the intended age-specific contact rates. `nodefactor(\"age\", levels = TRUE)` returns the total degree of each group, which divided by group size is the mean degree. The household row is repeated for comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_degree_by_age <- function(est, counts) {\n  dx <- netdx(est, nsims = 10, dynamic = FALSE, verbose = FALSE,\n              nwstats.formula = ~edges + nodemix(\"age\", levels2 = TRUE) +\n                                 nodefactor(\"age\", levels = TRUE))\n  st <- colMeans(do.call(rbind, lapply(dx$stats, as.matrix)))\n  st <- st[grep(\"^nodefactor\", names(st))]\n  names(st) <- sub(\"nodefactor.age.\", \"\", names(st))\n  round(st / as.numeric(counts[names(st)]), 2)\n}\ndeg_by_age <- rbind(household = deg_hh_by_age[names(counts)],\n                    community = mean_degree_by_age(est_com, counts))\nknitr::kable(deg_by_age, caption = \"Realized mean degree by age group and layer\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Realized mean degree by age group and layer\n\n|          | adult| elderly| infant| school| young|\n|:---------|-----:|-------:|------:|------:|-----:|\n|household |  1.76|    0.85|   2.76|   2.74|  2.61|\n|community |  4.99|    3.08|   2.25|   6.89|  5.34|\n\n\n:::\n:::\n\n\n## Custom Modules\n\nThree custom modules: `init_attrs` (one-shot setup of immunization status and the I substage), `infect` (S to E across both layers, with every transmission recorded), and `progress` (E to I~p~ to I~s~ to R or E to I~a~ to R, plus the age-stratified counters). Full code is in `module-fx.R`; the parts that carry the model's logic are below.\n\n### `infect`: a static layer and a simulated layer, walked the same way\n\nThe household edgelist is passed to `netsim` as the parameter `hh.pairs`, so the infection module can read it with `get_param()` on every step, exactly as it reads the community layer's current edgelist with `get_edgelist()`. Everything downstream of that line is layer-agnostic. Each layer contributes its successful exposures to one table, and the infections are resolved after both layers have been walked.\n\n```r\nhh_el <- get_param(dat, \"hh.pairs\")\ndel <- NULL\nfor (k in 1:2) {\n  el <- if (k == 1) hh_el else get_edgelist(dat, network = 1)         # <1>\n  if (is.null(el) || nrow(el) == 0) next\n\n  head <- el[, 1]; tail <- el[, 2]\n  if (k == 2 && com.contact.mult < 1) {                               # <2>\n    keep <- which(rbinom(nrow(el), 1, com.contact.mult) == 1)\n    head <- head[keep]; tail <- tail[keep]\n  }\n\n  # ... identify (sus, inf) pairs on this layer's discordant edges ...\n\n  base.p <- layer_probs[k]\n  stages <- inf_stage[inf]\n  trans.p <- ifelse(stages %in% \"ia\", base.p * asymp.mult, base.p)   # <3>\n\n  trans.p <- trans.p * as.numeric(sus.mult[age[sus]])                 # <4>\n  vax <- vax_status[sus]\n  eff <- rep(0, length(sus))\n  eff[!is.na(vax) & vax == \"elderly_vax\"] <- eff.inf.elderly\n  eff[!is.na(vax) & vax == \"infant_proph\"] <- eff.inf.infant\n  eff[!is.na(vax) & vax == \"cocoon\"] <- eff.inf.cocoon\n  trans.p <- trans.p * (1 - eff)                                      # <5>\n\n  hit <- which(rbinom(length(trans.p), 1, trans.p) == 1)\n  if (length(hit) > 0) {\n    del <- rbind(del, data.frame(sus = sus[hit], inf = inf[hit], layer = k))\n  }\n}\n\nif (!is.null(del) && nrow(del) > 0) {\n  del <- del[sample.int(nrow(del)), , drop = FALSE]                   # <6>\n  del <- del[!duplicated(del$sus), , drop = FALSE]\n\n  new_inf <- del$sus\n  status[new_inf] <- \"e\"\n  infTime[new_inf] <- at\n  dat <- set_attr(dat, \"status\", status)\n  dat <- set_attr(dat, \"infTime\", infTime)\n\n  del$at <- at                                                        # <7>\n  del$susAge <- age[del$sus]\n  del$infAge <- age[del$inf]\n  del$infTime <- infTime[del$inf]\n  dat <- set_transmat(dat, del, at)\n  # ... per-layer counts for the epi output ...\n}\n```\n1. **Two sources, one loop.** Layer 1 is the fixed household edgelist from the parameter list; layer 2 is the community TERGM, the only network `netsim` knows about, hence `network = 1`. Walking each layer separately, instead of calling `discord_edgelist()`, is what allows different transmission probabilities per layer.\n2. **NPI contact thinning.** While the NPI is active, each community edge is kept with probability `npi.contact.mult`, an approximation to a reduced contact rate. `layer_probs[2]` is also multiplied by `(1 - npi.mask.efficacy)` during the window.\n3. **Infectious-side modifier.** Asymptomatic partners transmit at half the rate.\n4. **Age-specific susceptibility.** The proxy for prior immunity: the per-contact probability is scaled by `sus.mult` for the susceptible partner's age, relative to a never-infected infant.\n5. **Infection-blocking component of immunization.** A leaky reduction for immunized susceptibles. This is the only product effect that reduces transmission to others, and for cocooning it is the whole effect.\n6. **Competing exposures.** Every discordant edge on both layers is a separate Bernoulli trial. A susceptible node with more than one successful exposure in the same step is infected once, and its infector, and hence its layer, is a uniform random draw among the successes: shuffle the successful exposures, then keep the first row per node. This is the tie-breaking rule EpiModel's built-in infection module uses. An earlier version attributed every simultaneous success to the household, which biased the layer shares.\n7. **Transmission record.** `set_transmat()` stores the rows for this step, and `netsim` binds them into one table per simulation that `get_transmat()` returns. Extra columns ride along, so the record carries the layer, both ages, and the infector's own infection time (1 for the seeds), which is what the who-infects-whom analysis below uses.\n\n### `init_attrs`: household ids make household targeting definable\n\nEvery co-resident of an infant, of any age, is eligible for the cocooning product. The comparator draws the same number of people of the same ages from the whole population, so the two arms differ only in whether the recipients live with an infant.\n\n```r\ninfant_hh <- unique(hh_id[active == 1 & age == \"infant\"])\nelig_c <- which(active == 1 & age != \"infant\" & hh_id %in% infant_hh)\nif (length(elig_c) > 0 && cocoon.cov > 0) {\n  hit <- elig_c[rbinom(length(elig_c), 1, cocoon.cov) == 1]\n  if (cocoon.random == 1 && length(hit) > 0) {\n    n_by_age <- table(age[hit])\n    hit <- unlist(lapply(names(n_by_age), function(a) {\n      pool <- which(active == 1 & age == a)\n      pool[sample.int(length(pool), n_by_age[[a]])]\n    }))\n  }\n  vax_status[hit] <- \"cocoon\"\n}\n```\n\n### `progress`: counters that make the analysis possible\n\nHospitalizations are computed after the fact, so `progress` records cumulative incident infections by age, and separately among immunized infants and older adults, so that the severity-reducing component of each product can be applied only where it belongs and the realized effectiveness among recipients can be computed. Seed infections from `init.net()` carry `infTime = 1` and are excluded. The numbers of immunized people are recorded too, so that doses are counted from the simulation rather than as coverage times a population.\n\n```r\nincident <- is_active & !is.na(infTime) & infTime > 1\nfor (a in c(\"infant\", \"young\", \"school\", \"adult\", \"elderly\")) {\n  dat <- set_epi(dat, paste0(\"cuminf.\", a), at, sum(incident & age == a))\n}\ninf_prot <- is_active & vax_status %in% \"infant_proph\"\neld_prot <- is_active & vax_status %in% \"elderly_vax\"\ndat <- set_epi(dat, \"cuminf.infant.prot\", at, sum(incident & inf_prot))\ndat <- set_epi(dat, \"cuminf.elderly.prot\", at, sum(incident & eld_prot))\ndat <- set_epi(dat, \"n.infant.prot\", at, sum(inf_prot))\ndat <- set_epi(dat, \"n.elderly.prot\", at, sum(eld_prot))\ndat <- set_epi(dat, \"n.cocoon\", at, sum(is_active & vax_status %in% \"cocoon\"))\n```\n\n### Module order\n\nEpiModel's default order runs user-supplied modules *before* the built-in ones, which here would run `progress` ahead of `infect` within each step. The order is set explicitly in `control.net()` so that each step runs\n\n```\nresim_nets -> summary_nets -> initAttr -> infection -> progress -> nwupdate -> prevalence\n```\n\nWith infection before progression, `progress` requires `infTime < at` for the E to I transition, which excludes infections written in the same step and guarantees at least one step in E.\n\n## Disease, Immunity, and Intervention Parameters\n\n**Natural history.** Mean latent period 4 days (the pooled median incubation period for RSV is 4.4 days; [Lessler et al. 2009](https://doi.org/10.1016/S1473-3099(09)70069-6)), presymptomatic 2 days, symptomatic or asymptomatic 7 days (mean shedding of 6.7 days in hospitalized infants; [Hall et al. 1976](https://doi.org/10.1016/s0022-3476(76)80918-3)), 30% of infections asymptomatic at half infectiousness. Every duration is geometric. The natural history does not vary by age, although infants shed longer and adults shorter; age-dependent durations are a natural extension.\n\n**Seasonal forcing.** RSV is strongly seasonal, and its seasons end because transmissibility falls, not only because susceptible people run out. Both layers' transmission probabilities are multiplied by a cosine with a period of one year, $1 + \\text{seas.amp} \\cos(2\\pi (t - \\text{seas.peak}) / 365)$, with the peak on day 1 so that the run starts at the top of the season and follows its decline. The forcing does two things for the example. It gives the epidemic a season-shaped curve that is over by about day 120, so the outcomes reported through day 150 are final sizes rather than snapshots of an ongoing epidemic. And it narrows the final-size distribution: without forcing, the same attack rates require an epidemic that barely grows, and the between-simulation coefficient of variation of season totals roughly doubles, which makes every intervention comparison noisier. The Scenario Modeling Hub asks teams to include their own seasonality; the amplitude here is illustrative.\n\n**Prior immunity.** In the Houston Family Study 69% of infants were infected in their first year and 83% in their second, and by age 4 the annual reinfection risk had fallen to about a third ([Glezen et al. 1986](https://doi.org/10.1001/archpedi.1986.02140200053026)); about 7% of healthy working adults ([Hall et al. 2001](https://doi.org/10.1086/322657)) and 3-7% of healthy older adults ([Falsey et al. 2005](https://doi.org/10.1056/NEJMoa043951)) are infected each year. Transmission models of RSV represent this with progressively reduced susceptibility after each infection ([Pitzer et al. 2015](https://doi.org/10.1371/journal.ppat.1004591)). This example uses age as a proxy for exposure history: `sus.mult` scales per-contact susceptibility for each age group relative to a never-infected infant. The per-contact transmission probabilities, the forcing amplitude, and `sus.mult` were chosen together, by iterating the baseline scenario, so that the season-long attack rates land near that gradient: 50-70% of infants, 40-60% of 1-4 year olds, 20-30% of school-age children, 7-10% of adults (parents of young children run higher than the healthy-worker figure), and 3-7% of older adults. The baseline attack rates are reported below so that the reader can check the run in hand against these ranges. They are illustrative, not fitted to data.\n\n**Products.** Each product has two leaky components, following how the products are evaluated in trials and how other RSV scenario models represent them: `eff.inf` reduces the per-contact probability of infection, and `eff.hosp` reduces the hospitalization risk given infection. Against a single exposure the two combine to $1 - (1 - \\text{eff.inf})(1 - \\text{eff.hosp}) = 0.80$ for both products, the first-season effectiveness against hospitalization assumed by the RSV Scenario Modeling Hub ([Round 4, 2026-27 season](https://github.com/midas-network/rsv-scenario-modeling-hub#intervention-effectiveness): 80% for infant monoclonals and for older-adult vaccines in the year of vaccination). That equality holds per exposure, not per season. Because `eff.inf` is leaky and acts per contact, a recipient who is exposed repeatedly over the season is protected against infection by less than `eff.inf`, so the product's *realized* effectiveness against hospitalization over the season is an output of the model. The analysis computes it from the attack rates among immunized and unimmunized members of each group and reports it next to the 80% input. The split between the two components is an assumption: setting `eff.inf = 0` and `eff.hosp = 0.80` gives a product with the same per-exposure effectiveness, no indirect effect, and a realized effectiveness of exactly 80% by construction. The Gallery's [all-or-nothing](../seir-aon-vaccination/) and [leaky](../seirs-leaky-vaccination/) vaccination examples treat the distinction at length.\n\n**Cocooning and its comparator.** Every co-resident of an infant (parents, siblings, grandparents) receives a *hypothetical* product with the older-adult vaccine's infection-blocking component (`cocoon.eff.inf = 0.5`) and no severity component. No product is currently recommended for this purpose, and maternal vaccination protects the infant through antibody transfer rather than by blocking the parent's transmission. The scenario is here because it is the question an explicit household layer makes answerable: how much infant protection can blocking household transmission deliver, at most, compared with a product given to the infant? Complete coverage makes it an upper bound. The equal-dose comparator gives the same number of doses of the same product to people of the same ages drawn at random from the whole population, so the difference between the two arms is the value of the household link itself.\n\n::: {.callout-important}\n## Simplifications relative to current guidance and trial evidence\n\n- **Eligibility.** The model immunizes a random fraction of all infants and of all adults 65+. Current CDC guidance is nirsevimab (or clesrovimab) for infants entering their first RSV season, or maternal vaccination during pregnancy, and a single vaccine dose for adults 75+ and adults 50-74 at increased risk of severe disease. The model has no births, so the in-season birth cohort and maternal vaccination are not represented, and infants are one stratum rather than an age in months.\n- **Efficacy endpoints.** Trials report efficacy against medically attended RSV lower respiratory tract illness: 74.5% for nirsevimab in the MELODY trial ([Hammitt et al. 2022](https://doi.org/10.1056/NEJMoa2110275)) and 79.5% pooled, with 77.3% against hospitalization ([Simões et al. 2023](https://doi.org/10.1016/S2352-4642(22)00321-2)); 82.6% for the adjuvanted older-adult vaccine ([Papi et al. 2023](https://doi.org/10.1056/NEJMoa2209604)) and 66.7% to 85.7% depending on case definition for the bivalent vaccine ([Walsh et al. 2023](https://doi.org/10.1056/NEJMoa2213836)). None of these trials measured protection against infection itself.\n- **Waning.** Product protection is constant within the season. Nirsevimab protects for at least 150 days and the older-adult vaccines for more than one season with declining effectiveness, so a single-season model does not need waning, but a multi-season extension would.\n- **Household ties are unweighted.** Within a household every pair transmits at the same per-contact probability, so a parent-infant tie and a sibling-infant tie are identical. Weighting ties by relationship is a natural extension once households are explicit.\n:::\n\n### Parameter provenance\n\n| Parameter | Value | Units and endpoint | Basis | Status |\n|---|---|---|---|---|\n| `hh_types` | table above | probability of each household composition | person-level age shares and mean household size of the United States; sibling and living-alone shares | illustrative |\n| `com_profile` | table above | daily community contacts per person, by age pair | qualitative pattern of POLYMOD (Mossong 2008): assortative, highest among school-age children | illustrative |\n| `inf.prob.household`, `inf.prob.community` | 0.35, 0.08 | annual-mean per-contact, per-day probability of transmission to a never-infected infant, scaled by the seasonal multiplier | tuned, with `sus.mult` and the forcing amplitude, to the attack-rate gradient below | illustrative |\n| `seas.amp`, `seas.peak` | 0.5, day 1 | amplitude of the annual cosine forcing on both layers; day of peak transmissibility | RSV seasons are forced; the run starts at the peak and follows the decline | illustrative |\n| `sus.mult` | 1.00 / 0.55 / 0.16 / 0.07 / 0.13 | relative per-contact susceptibility (infant / young / school / adult / elderly) | tuned to season attack rates of 50-70%, 40-60%, 20-30%, 7-10%, 3-7% (Glezen 1986, Hall 2001, Falsey 2005) | illustrative |\n| `ei.rate` | 1/4 | mean latent period, days | RSV incubation 4.4 days (Lessler 2009) | literature |\n| `ip.rate`, `ir.rate` | 1/2, 1/7 | mean presymptomatic and symptomatic or asymptomatic periods, days | shedding about a week (Hall 1976) | approximate |\n| `asymp.prob`, `asymp.inf.mult` | 0.3, 0.5 | share asymptomatic; relative infectiousness | assumption | illustrative |\n| `elderly.vax.eff.inf`, `elderly.vax.eff.hosp` | 0.5, 0.6 | per-contact reduction in infection; reduction in hospitalization given infection | combine to 80% per exposure, the Hub's first-year value; trials 67-83% against medically attended illness | Hub-aligned total, assumed split |\n| `infant.proph.eff.inf`, `infant.proph.eff.hosp` | 0.3, 0.71 | as above | combine to 80% per exposure, the Hub's value; trials 74-80% | Hub-aligned total, assumed split |\n| `cocoon.eff.inf` | 0.5 | per-contact reduction in infection for co-residents of infants | hypothetical product | hypothetical |\n| coverage | 50% of 65+, 60% of infants, 100% of infant co-residents | share immunized before the season | Hub \"usual\" coverage for 2026-27: 56% of infants, 50% of adults 75+; complete coverage for the hypothetical cocoon | Hub-aligned, simplified eligibility |\n| `npi.mask.efficacy`, `npi.contact.mult` | 0.4, 0.7 | community per-contact reduction; share of community contacts kept, days 30-90 | hypothetical | hypothetical |\n| `hosp_rate` | 0.030 / 0.006 / 0.001 / 0.004 / 0.045 | hospitalizations per infection, by age | chosen so the baseline lands near the RSV-NET age pattern | illustrative |\n| `N`, `nsteps`, seeds | 10,000; 150 days; 1% infectious at day 1 | population; season length; initial conditions | a five-month season; 1% seeds start the epidemic without a long stochastic lag | design |\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninit <- init.net(i.num = round(0.01 * N))                             # <1>\n\nparam_base <- param.net(\n  inf.prob.household = 0.35,                                          # <2>\n  inf.prob.community = 0.08,\n  seas.amp = 0.5,                                                     # <3>\n  seas.peak = 1,\n  sus.mult = c(infant = 1.00, young = 0.55, school = 0.16,\n               adult = 0.07, elderly = 0.13),\n  asymp.inf.mult = 0.5,\n  ei.rate = 1 / 4,\n  ip.rate = 1 / 2,\n  ir.rate = 1 / 7,\n  asymp.prob = 0.3,\n  elderly.vax.coverage = 0,                                           # <4>\n  elderly.vax.eff.inf = 0.5,\n  elderly.vax.eff.hosp = 0.6,\n  infant.proph.coverage = 0,\n  infant.proph.eff.inf = 0.3,\n  infant.proph.eff.hosp = 0.71,\n  cocoon.coverage = 0,\n  cocoon.eff.inf = 0.5,\n  cocoon.random = 0,\n  npi.start = -1,\n  npi.end = -1,\n  npi.mask.efficacy = 0.4,\n  npi.contact.mult = 0.7,\n  hh.pairs = hh_el                                                    # <5>\n)\n\ncontrol <- control.net(\n  type = NULL,\n  nsims = nsims, ncores = ncores, nsteps = nsteps,\n  tergmLite = TRUE,\n  resimulate.network = TRUE,\n  initAttr.FUN = init_attrs,\n  infection.FUN = infect,\n  progress.FUN = progress,\n  module.order = c(\"resim_nets.FUN\", \"summary_nets.FUN\", \"initAttr.FUN\",\n                   \"infection.FUN\", \"progress.FUN\", \"nwupdate.FUN\",\n                   \"prevalence.FUN\"),\n  verbose = FALSE\n)\n```\n:::\n\n1. One percent of the population is seeded as infectious at the start of the season, placed at random across ages. Seeds are excluded from the incidence counters.\n2. Annual-mean per-contact, per-day transmission probabilities, which the seasonal multiplier scales up to 1.5 times at the start of the run. Household contacts are higher-intensity than community contacts. With `sus.mult = 0.07` for adults, an adult living with one infectious household member has about a 20% chance of infection over a 9-day infectious period at the annual mean and about 29% at the seasonal peak; for a never-infected infant the corresponding risks are 98% and above 99%, so the household layer is close to saturating for infants and what matters is whether a co-resident gets infected at all.\n3. Seasonal forcing: both layers' probabilities are multiplied by $1 + 0.5 \\cos(2\\pi (t - 1) / 365)$, so transmissibility starts at 1.5 times the annual mean on day 1 and falls to about 0.6 times it by day 150.\n4. Intervention coverages default to zero and the NPI window to inactive, so the base parameter set is the no-intervention scenario. Scenarios override these below.\n5. The household edgelist rides along in the parameter list. `param.net()` accepts non-scalar entries, and `use_scenario()` leaves entries the scenario does not name untouched.\n\n## Scenarios\n\nSeven scenarios on the same network with identical disease parameters. Product coverage follows the \"usual\" assumptions of the RSV Scenario Modeling Hub for the 2026-27 season (56% of infants receiving a monoclonal antibody, 50% of adults 75+ vaccinated). The household cocoon covers every co-resident of an infant; the random arm gives the same number of doses to people of the same ages drawn from the whole population. The NPI is a strong hypothetical: for days 30 to 90, community contacts are cut by 30% and the remaining community contacts transmit at 60% of the usual rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscenarios.df <- data.frame(\n  .scenario.id          = c(\"none\", \"elderly_vax\", \"infant_proph\", \"both\",\n                            \"cocoon\", \"cocoon_random\", \"npi\"),\n  .at                   = 0,\n  elderly.vax.coverage  = c(0, 0.5, 0, 0.5, 0, 0, 0),\n  infant.proph.coverage = c(0, 0, 0.6, 0.6, 0, 0, 0),\n  cocoon.coverage       = c(0, 0, 0, 0, 1, 1, 0),\n  cocoon.random         = c(0, 0, 0, 0, 0, 1, 0),\n  npi.start             = c(-1, -1, -1, -1, -1, -1, 30),\n  npi.end               = c(-1, -1, -1, -1, -1, -1, 90)\n)\nscenarios.list <- create_scenario_list(scenarios.df)\n\nlabels <- c(none = \"No intervention\",\n            elderly_vax = \"Older-adult vaccine (50%)\",\n            infant_proph = \"Infant antibody (60%)\",\n            both = \"Both products\",\n            cocoon = \"Household cocoon (all co-residents of infants)\",\n            cocoon_random = \"Same doses, random people of the same ages\",\n            npi = \"NPI (days 30-90)\")\n\nsims <- list()\nfor (scn in scenarios.list) {\n  sims[[scn$id]] <- netsim(est_com, use_scenario(param_base, scn),\n                           init, control)\n}\n```\n:::\n\n\n## Analysis\n\n### From infections to hospitalizations\n\nExpected hospitalizations in each simulation are infections times the age-specific risk, minus the severity reduction for infections among immunized people. The per-infection risks are illustrative, chosen so that the baseline season lands near the age pattern of RSV-NET hospitalization rates (highest in infants, then older adults, lowest in school-age children) given the attack rates above. The summary keeps one row per simulation for every quantity, which is what the Monte Carlo intervals below are built from. Doses are the numbers of people actually immunized in the simulation, and the number needed to immunize (NNI) is doses per hospitalization averted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhosp_rate <- c(infant = 0.030, young = 0.006, school = 0.001,\n               adult = 0.004, elderly = 0.045)\neff_hosp <- c(infant = param_base$infant.proph.eff.hosp,\n              elderly = param_base$elderly.vax.eff.hosp)\n\nage_groups <- c(\"infant\", \"young\", \"school\", \"adult\", \"elderly\")\nage_pop <- as.numeric(counts[age_groups])\nnames(age_pop) <- age_groups\n\nsummarize_scenario <- function(sim) {\n  df <- as.data.frame(sim)\n  last <- df[df$time == max(df$time), ]           # one row per simulation\n  hosp_sim <- sapply(age_groups, function(a) {\n    last[[paste0(\"cuminf.\", a)]] * hosp_rate[a]\n  })\n  hosp_sim <- matrix(hosp_sim, ncol = length(age_groups),\n                     dimnames = list(NULL, age_groups))\n  for (a in c(\"infant\", \"elderly\")) {\n    hosp_sim[, a] <- hosp_sim[, a] -\n      last[[paste0(\"cuminf.\", a, \".prot\")]] * hosp_rate[a] * eff_hosp[a]\n  }\n  inf <- sapply(age_groups, function(a) mean(last[[paste0(\"cuminf.\", a)]]))\n  attack_prot <- attack_unprot <- matrix(NA_real_, nrow(last), 2,\n                                         dimnames = list(NULL, c(\"infant\", \"elderly\")))\n  for (a in c(\"infant\", \"elderly\")) {\n    n_p <- last[[paste0(\"n.\", a, \".prot\")]]\n    i_p <- last[[paste0(\"cuminf.\", a, \".prot\")]]\n    attack_prot[, a] <- ifelse(n_p > 0, i_p / n_p, NA)\n    attack_unprot[, a] <- (last[[paste0(\"cuminf.\", a)]] - i_p) / (age_pop[a] - n_p)\n  }\n  doses <- mean(last$n.elderly.prot + last$n.infant.prot + last$n.cocoon)\n  hh_share_infant <- sum(df$se.flow.infant.hh, na.rm = TRUE) /\n    sum(df$se.flow.infant.hh + df$se.flow.infant.com, na.rm = TRUE)\n  active_end <- mean(last$e.num + last$ip.num + last$is.num + last$ia.num)\n  list(inf = inf, attack = inf / age_pop,\n       hosp = colMeans(hosp_sim), hosp_sim = hosp_sim,\n       hosp_per100k = 1e5 * colMeans(hosp_sim) / age_pop,\n       attack_prot = attack_prot, attack_unprot = attack_unprot,\n       doses = doses, hh_share_infant = hh_share_infant,\n       active_end = active_end, cuminf_end = sum(inf))\n}\n\nres <- lapply(sims, summarize_scenario)\n```\n:::\n\n\n### Attack rates and hospitalization burden\n\nAll outcomes are cumulative through day 150. The last table in this section checks how much of the season was still in progress at that point.\n\n\n::: {#tbl-attack .cell}\n\n```{.r .cell-code}\nattack_tbl <- sapply(res, function(r) round(100 * r$attack, 1))\nknitr::kable(attack_tbl,\n             caption = \"Cumulative attack rate through the end of the run by age group (%), mean of simulations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cumulative attack rate through the end of the run by age group (%), mean of simulations\n\n|        | none| elderly_vax| infant_proph| both| cocoon| cocoon_random|  npi|\n|:-------|----:|-----------:|------------:|----:|------:|-------------:|----:|\n|infant  | 56.8|        53.8|         53.2| 51.1|   47.0|          52.7| 28.0|\n|young   | 61.5|        59.5|         60.7| 59.9|   56.5|          55.6| 30.8|\n|school  | 28.3|        27.3|         26.3| 25.2|   24.6|          24.7| 12.4|\n|adult   |  9.4|         8.9|          9.0|  8.9|    8.4|           8.2|  4.4|\n|elderly |  5.4|         3.6|          5.1|  3.6|    4.9|           4.4|  2.6|\n\n\n:::\n:::\n\n\nThe baseline column is the check against the literature ranges stated above (50-70%, 40-60%, 20-30%, 7-10%, and 3-7%): 56.8% of infants, 61.5% of young children, 28.3% of school-age children, 9.4% of adults, and 5.4% of older adults infected in the season. Young children land at the top of their range because siblings and child care expose them heavily in this model, and adults who live with children run above the healthy-worker attack rate; both are what an explicit household layer produces.\n\n\n::: {#tbl-hosp .cell}\n\n```{.r .cell-code}\nhosp100k_tbl <- rbind(\n  sapply(res, function(r) round(r$hosp_per100k)),\n  total = sapply(res, function(r) round(1e5 * sum(r$hosp) / N))\n)\nknitr::kable(hosp100k_tbl,\n             caption = \"Expected hospitalizations per 100,000 population, by age group (rows) and scenario; the total row is per 100,000 of all ages\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Expected hospitalizations per 100,000 population, by age group (rows) and scenario; the total row is per 100,000 of all ages\n\n|        | none| elderly_vax| infant_proph| both| cocoon| cocoon_random| npi|\n|:-------|----:|-----------:|------------:|----:|------:|-------------:|---:|\n|infant  | 1705|        1615|          945|  916|   1410|          1582| 841|\n|young   |  369|         357|          364|  359|    339|           334| 185|\n|school  |   28|          27|           26|   25|     25|            25|  12|\n|adult   |   38|          36|           36|   36|     33|            33|  17|\n|elderly |  243|         128|          228|  129|    219|           199| 115|\n|total   |  110|          86|           97|   78|     97|            95|  53|\n\n\n:::\n:::\n\n\nThe hospitalization rates are within the range that RSV-NET reports for a season: on the order of 1,000 to 2,500 per 100,000 in infants, 100 to 300 per 100,000 in adults 65+, tens per 100,000 in adults 18-64, and about 100 per 100,000 overall. Older adults and infants together account for 58% of baseline hospitalizations even though they are a fifth of the population. Because the per-infection risks were chosen to reproduce that pattern, the hospitalization table is not an independent check of the transmission model; the attack-rate table and the transmission matrix below are.\n\n\n::: {#tbl-window .cell}\n\n```{.r .cell-code}\nknitr::kable(t(sapply(res, function(r) round(100 * r$active_end / r$cuminf_end, 1))),\n             caption = \"Infections still in progress (E or I) at the last day, as a percent of the season's cumulative infections\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Infections still in progress (E or I) at the last day, as a percent of the season's cumulative infections\n\n| none| elderly_vax| infant_proph| both| cocoon| cocoon_random| npi|\n|----:|-----------:|------------:|----:|------:|-------------:|---:|\n|  0.3|         0.3|          0.4|  0.3|    0.3|           0.4| 0.2|\n\n\n:::\n:::\n\n\nThe observation window matters for interpretation. With 0.3% of the baseline season's infections still in progress on day 150, the scenario comparisons are about final size rather than timing, and a strategy that only delayed infections would show up here as a larger in-progress share, which the NPI does not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncols_scn <- c(none = \"gray40\", elderly_vax = \"seagreen\",\n              infant_proph = \"purple\", both = \"darkblue\",\n              cocoon = \"darkorange\", cocoon_random = \"goldenrod\",\n              npi = \"firebrick\")\nlty_scn <- c(none = 1, elderly_vax = 1, infant_proph = 1, both = 1,\n             cocoon = 1, cocoon_random = 2, npi = 1)\npar(mfrow = c(2, 3), mar = c(3, 3.5, 2, 1), mgp = c(2.2, 0.7, 0))\nfor (a in age_groups) {\n  col_name <- paste0(\"cuminf.\", a)\n  curves <- lapply(names(sims), function(s) {\n    df <- as.data.frame(sims[[s]])\n    tapply(df[[col_name]], df$time, mean, na.rm = TRUE) / age_pop[a]\n  })\n  names(curves) <- names(sims)\n  max_y <- max(sapply(curves, max, na.rm = TRUE))\n  plot(NA, xlim = c(1, nsteps), ylim = c(0, max(max_y, 0.01) * 1.05),\n       xlab = \"Day\", ylab = \"Cumulative attack rate\",\n       main = paste0(toupper(substr(a, 1, 1)), substr(a, 2, nchar(a)),\n                    \" (N=\", age_pop[a], \")\"))\n  for (s in names(sims)) {\n    lines(as.numeric(names(curves[[s]])), curves[[s]], lwd = 2,\n          col = cols_scn[s], lty = lty_scn[s])\n  }\n}\nplot.new()\nlegend(\"center\", legend = labels, col = cols_scn, lwd = 2, lty = lty_scn,\n       bty = \"n\", cex = 0.8)\n```\n\n::: {.cell-output-display}\n![Cumulative attack rate (cumulative incident infections divided by age-group population) by age group and scenario, mean of simulations. The y-axis scale differs by panel.](index_files/figure-html/fig-age-strat-1.png){#fig-age-strat width=960}\n:::\n:::\n\n\nThe product scenarios move mainly their own panel: the infant antibody lowers the infant curve and the older-adult vaccine lowers the elderly curve. The household cocoon lowers the infant curve without immunizing any infant, and the random arm, with the same doses, moves it much less. The NPI lowers every panel because it acts on the children who feed infections into the other groups. Movements in the untargeted panels are within the between-simulation noise quantified below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncols_age <- c(infant = \"#3498db\", young = \"#f39c12\", school = \"#e74c3c\",\n              adult = \"#27ae60\", elderly = \"#8e44ad\")\nhosp_mat <- sapply(res, function(r) 1e5 * r$hosp / N)\ntot <- colSums(hosp_mat)\npar(mar = c(7, 4.5, 5, 1), mgp = c(3, 1, 0))\nbp <- barplot(hosp_mat, names.arg = names(sims), las = 2,\n              col = cols_age[age_groups],\n              ylab = \"Hospitalizations per 100,000 population\",\n              main = \"Season Hospitalization Burden by Age\",\n              ylim = c(0, max(tot) * 1.15))\ntext(bp, tot + max(tot) * 0.04, sprintf(\"%.0f\", tot), cex = 0.9, font = 2)\nlegend(\"top\", legend = age_groups, horiz = TRUE, fill = cols_age[age_groups],\n       bty = \"n\", cex = 0.9, inset = c(0, -0.18), xpd = TRUE)\n```\n\n::: {.cell-output-display}\n![Expected hospitalizations per 100,000 population by scenario, stacked by age group. Bar labels are the all-ages total.](index_files/figure-html/fig-hosp-1.png){#fig-hosp width=768}\n:::\n:::\n\n\n### Hospitalizations averted, with uncertainty\n\nEach scenario is compared with the baseline on the per-simulation hospitalization counts, and every difference carries a 95% Monte Carlo interval from the between-simulation variance of the two arms. Averted hospitalizations and the NNI are computed within the age groups each strategy is designed to protect (older adults for the vaccine, infants for the antibody, for the cocoon, and for its random comparator, both for the combined arm, all ages for the NPI), and the all-ages difference is reported next to them with its own interval. The two columns together show why the target-group version is the one to read for the products: the untargeted strata are large, their between-simulation noise is comparable to a product's whole effect, and the all-ages intervals are correspondingly wide. NNI is reported only when the point estimate of averted hospitalizations is positive, and with an interval only when the whole interval for averted hospitalizations is positive.\n\n\n::: {#tbl-int .cell}\n\n```{.r .cell-code}\nmc_diff <- function(x0, x1) {\n  d <- mean(x0) - mean(x1)\n  if (length(x0) < 2 || length(x1) < 2) return(c(est = d, lo = NA, hi = NA))\n  se <- sqrt(var(x0) / length(x0) + var(x1) / length(x1))\n  c(est = d, lo = d - 1.96 * se, hi = d + 1.96 * se)\n}\nfmt_ci <- function(v, digits = 1) {\n  if (is.na(v[\"lo\"])) return(sprintf(\"%.*f\", digits, v[\"est\"]))\n  sprintf(\"%.*f (%.*f, %.*f)\", digits, v[\"est\"], digits, v[\"lo\"], digits, v[\"hi\"])\n}\n\ntarget_groups <- list(none = age_groups, elderly_vax = \"elderly\",\n                      infant_proph = \"infant\", both = c(\"infant\", \"elderly\"),\n                      cocoon = \"infant\", cocoon_random = \"infant\",\n                      npi = age_groups)\nper100k <- function(r, groups) 1e5 * rowSums(r$hosp_sim[, groups, drop = FALSE]) / N\naverted <- lapply(names(res), function(s) {\n  tg <- target_groups[[s]]\n  list(target = mc_diff(per100k(res$none, tg), per100k(res[[s]], tg)),\n       all = mc_diff(per100k(res$none, age_groups), per100k(res[[s]], age_groups)),\n       base_target = mean(per100k(res$none, tg)))\n})\nnames(averted) <- names(res)\n\nnni_of <- function(s) {\n  a <- averted[[s]]$target\n  doses <- res[[s]]$doses\n  averted_n <- a * N / 1e5                  # per 100,000 -> count in N\n  if (doses == 0 || is.na(averted_n[\"est\"]) || averted_n[\"est\"] <= 0) return(NA_character_)\n  est <- doses / averted_n[\"est\"]\n  if (is.na(averted_n[\"lo\"]) || averted_n[\"lo\"] <= 0) {\n    return(sprintf(\"%.0f\", est))\n  }\n  sprintf(\"%.0f (%.0f, %.0f)\", est, doses / averted_n[\"hi\"], doses / averted_n[\"lo\"])\n}\n\nint_tbl <- data.frame(\n  Scenario = labels[names(res)],\n  `Target group` = sapply(names(res), function(s)\n    if (length(target_groups[[s]]) == 5) \"all ages\" else\n      paste(target_groups[[s]], collapse = \" + \")),\n  Doses = sapply(res, function(r) round(r$doses)),\n  `Averted in target group` = sapply(names(res), function(s) fmt_ci(averted[[s]]$target)),\n  `Percent of target-group baseline` = sapply(names(res), function(s) {\n    b <- averted[[s]]$base_target\n    if (b > 0) round(100 * averted[[s]]$target[\"est\"] / b, 1) else NA\n  }),\n  `Averted, all ages` = sapply(names(res), function(s) fmt_ci(averted[[s]]$all)),\n  NNI = sapply(names(res), nni_of),\n  check.names = FALSE, row.names = NULL\n)\nknitr::kable(int_tbl,\n             caption = \"Hospitalizations averted relative to no intervention, per 100,000 total population, in the target group and in all ages (95% Monte Carlo intervals in parentheses); doses delivered; and number needed to immunize (doses per hospitalization averted in the target group)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Hospitalizations averted relative to no intervention, per 100,000 total population, in the target group and in all ages (95% Monte Carlo intervals in parentheses); doses delivered; and number needed to immunize (doses per hospitalization averted in the target group)\n\n|Scenario                                       |Target group     | Doses|Averted in target group | Percent of target-group baseline|Averted, all ages |NNI             |\n|:----------------------------------------------|:----------------|-----:|:-----------------------|--------------------------------:|:-----------------|:---------------|\n|No intervention                                |all ages         |     0|0.0 (-8.5, 8.5)         |                              0.0|0.0 (-8.5, 8.5)   |NA              |\n|Older-adult vaccine (50%)                      |elderly          |   916|20.9 (16.3, 25.5)       |                             47.5|23.9 (15.7, 32.1) |439 (360, 563)  |\n|Infant antibody (60%)                          |infant           |    70|8.9 (7.4, 10.4)         |                             44.6|13.0 (4.4, 21.5)  |78 (67, 94)     |\n|Both products                                  |infant + elderly |   959|29.8 (24.8, 34.8)       |                             46.6|31.9 (24.4, 39.5) |322 (276, 387)  |\n|Household cocoon (all co-residents of infants) |infant           |   323|3.4 (1.6, 5.3)          |                             17.3|12.4 (2.8, 21.9)  |936 (608, 2034) |\n|Same doses, random people of the same ages     |infant           |   323|1.4 (-0.4, 3.3)         |                              7.2|14.4 (3.3, 25.5)  |2243            |\n|NPI (days 30-90)                               |all ages         |     0|57.1 (49.6, 64.6)       |                             52.1|57.1 (49.6, 64.6) |NA              |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscn_int <- setdiff(names(res), \"none\")\nav_est <- sapply(scn_int, function(s) averted[[s]]$target[\"est\"])\nav_lo <- sapply(scn_int, function(s) averted[[s]]$target[\"lo\"])\nav_hi <- sapply(scn_int, function(s) averted[[s]]$target[\"hi\"])\nshort <- c(elderly_vax = \"Older-adult vaccine\", infant_proph = \"Infant antibody\",\n           both = \"Both products\", cocoon = \"Household cocoon\",\n           cocoon_random = \"Random, same doses\", npi = \"NPI\")\npar(mfrow = c(1, 2), mar = c(9, 5, 3, 1), mgp = c(3.5, 1, 0))\nyr <- range(c(0, av_est, av_lo, av_hi), na.rm = TRUE)\nbp2 <- barplot(av_est, names.arg = short[scn_int], col = cols_scn[scn_int],\n               las = 2, cex.names = 0.8,\n               ylab = \"Averted per 100,000 population\",\n               main = \"Averted in Target Groups\",\n               ylim = yr + diff(yr) * c(-0.05, 0.15))\nabline(h = 0)\nif (!all(is.na(av_lo))) {\n  arrows(bp2, av_lo, bp2, av_hi, angle = 90, code = 3, length = 0.04)\n}\ntext(bp2, pmax(av_hi, av_est, na.rm = TRUE) + diff(yr) * 0.04,\n     sprintf(\"%.1f\", av_est), cex = 0.85, font = 2)\nnni_num <- sapply(scn_int, function(s) {\n  a <- averted[[s]]$target[\"est\"] * N / 1e5\n  if (res[[s]]$doses > 0 && !is.na(a) && a > 0) res[[s]]$doses / a else NA\n})\nkeep <- which(!is.na(nni_num))\nif (length(keep) > 0) {\n  bp3 <- barplot(nni_num[keep], names.arg = short[scn_int[keep]],\n                 col = cols_scn[scn_int[keep]], las = 2, cex.names = 0.8,\n                 ylab = \"Doses per hospitalization averted\",\n                 main = \"Number Needed to Immunize\",\n                 ylim = c(0, max(nni_num[keep]) * 1.25))\n  text(bp3, nni_num[keep] + max(nni_num[keep]) * 0.05,\n       sprintf(\"%.0f\", nni_num[keep]), cex = 0.85, font = 2)\n}\n```\n\n::: {.cell-output-display}\n![Hospitalizations averted in each strategy's target group, per 100,000 total population, with 95% Monte Carlo intervals (left), and doses per hospitalization averted for the strategies with a positive point estimate (right). The NPI has no dose denominator.](index_files/figure-html/fig-averted-1.png){#fig-averted width=864}\n:::\n:::\n\n\nTwo features of these results carry over to the published scenario models. First, the older-adult vaccine averts the most hospitalizations in absolute terms because older adults are a large group with a high per-infection risk, while the infant antibody is the more efficient product per dose (an NNI of 78 (67, 94) against 439 (360, 563) here) because infants have the highest per-infection risk but are about 1% of the population. Second, the two products are close to additive, since they act on different people. The cocoon rows are the ones to read with their intervals. Even a complete household cocoon averts 3.4 (1.6, 5.3) infant hospitalizations per 100,000, 17.3% of the infant baseline, at an NNI of 936 (608, 2034), many times the infant antibody's. The random arm, with the same doses to the same ages, averts 1.4 (-0.4, 3.3), an interval that includes zero, so most of the cocoon's infant effect comes from the household link rather than from immunizing that many people. Both arms also lower the all-ages total by a similar and imprecisely estimated amount, which is the indirect effect of giving several hundred people, including children, a transmission-blocking product.\n\n### Realized product effectiveness\n\nThe 80% effectiveness against hospitalization is an input per exposure. What a recipient experiences over a season depends on how often they are exposed, because the infection-blocking component is leaky. The realized effectiveness against infection among recipients is one minus the ratio of the attack rate among immunized to that among unimmunized members of the same group in the same scenario, and the realized effectiveness against hospitalization follows from it and the severity component.\n\n\n::: {#tbl-ve .cell}\n\n```{.r .cell-code}\nve_tbl <- do.call(rbind, lapply(c(\"elderly_vax\", \"infant_proph\"), function(s) {\n  a <- if (s == \"elderly_vax\") \"elderly\" else \"infant\"\n  r <- res[[s]]\n  ve_inf <- ifelse(r$attack_unprot[, a] > 0,\n                   1 - r$attack_prot[, a] / r$attack_unprot[, a], NA)\n  ve_hosp <- 1 - (1 - ve_inf) * (1 - eff_hosp[a])\n  ci <- function(v) {\n    m <- mean(v, na.rm = TRUE)\n    if (sum(!is.na(v)) < 2) return(sprintf(\"%.0f\", 100 * m))\n    se <- sd(v, na.rm = TRUE) / sqrt(sum(!is.na(v)))\n    sprintf(\"%.0f (%.0f, %.0f)\", 100 * m, 100 * (m - 1.96 * se), 100 * (m + 1.96 * se))\n  }\n  eff_inf <- if (a == \"elderly\") param_base$elderly.vax.eff.inf else param_base$infant.proph.eff.inf\n  data.frame(Product = labels[s], Group = a,\n             `eff.inf (per contact)` = 100 * eff_inf,\n             `Realized VE, infection` = ci(ve_inf),\n             `eff.hosp` = 100 * eff_hosp[a],\n             `VE, hospitalization, per exposure` = round(100 * (1 - (1 - eff_inf) * (1 - eff_hosp[a]))),\n             `Realized VE, hospitalization` = ci(ve_hosp),\n             check.names = FALSE, row.names = NULL)\n}))\nknitr::kable(ve_tbl,\n             caption = \"Product effectiveness among recipients (%): the per-contact and per-exposure inputs, and the realized season-long values from the simulation (95% Monte Carlo intervals in parentheses)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Product effectiveness among recipients (%): the per-contact and per-exposure inputs, and the realized season-long values from the simulation (95% Monte Carlo intervals in parentheses)\n\n|Product                   |Group   | eff.inf (per contact)|Realized VE, infection | eff.hosp| VE, hospitalization, per exposure|Realized VE, hospitalization |\n|:-------------------------|:-------|---------------------:|:----------------------|--------:|---------------------------------:|:----------------------------|\n|Older-adult vaccine (50%) |elderly |                    50|45 (32, 58)            |       60|                                80|78 (73, 83)                  |\n|Infant antibody (60%)     |infant  |                    30|6 (-2, 14)             |       71|                                80|73 (70, 75)                  |\n\n\n:::\n:::\n\n\nFor older adults, who are exposed rarely, the realized effectiveness against infection is close to the per-contact input and the realized effectiveness against hospitalization is close to the 80% assumed. For infants, who are exposed repeatedly at home, the leaky component protects little over the season (6% against infection from a per-contact input of 30%), and the realized effectiveness against hospitalization is 73% rather than 80%. A model that wants the Hub's 80% to hold at the season level for infants should either put more of the effect into the severity component or use an all-or-nothing infection-blocking component.\n\n### Indirect effects\n\nThe indirect effect of each strategy is read from the attack rate among people who did *not* receive it, with a Monte Carlo interval:\n\n\n::: {#tbl-indirect .cell}\n\n```{.r .cell-code}\nunprot_tbl <- sapply(res, function(r) sapply(c(\"infant\", \"elderly\"), function(a) {\n  v <- 100 * r$attack_unprot[, a]\n  if (length(v) < 2) return(sprintf(\"%.1f\", mean(v)))\n  se <- sd(v) / sqrt(length(v))\n  sprintf(\"%.1f (%.1f, %.1f)\", mean(v), mean(v) - 1.96 * se, mean(v) + 1.96 * se)\n}))\nknitr::kable(unprot_tbl,\n             caption = \"Cumulative attack rate (%) among unimmunized infants and older adults, by scenario, mean of simulations (95% Monte Carlo intervals in parentheses)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Cumulative attack rate (%) among unimmunized infants and older adults, by scenario, mean of simulations (95% Monte Carlo intervals in parentheses)\n\n|        |none              |elderly_vax       |infant_proph      |both              |cocoon            |cocoon_random     |npi               |\n|:-------|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|:-----------------|\n|infant  |56.8 (53.8, 59.9) |53.8 (50.2, 57.5) |55.5 (50.4, 60.6) |54.0 (48.1, 60.0) |47.0 (42.7, 51.4) |52.7 (48.6, 56.9) |28.0 (23.7, 32.4) |\n|elderly |5.4 (4.9, 5.8)    |4.7 (4.1, 5.3)    |5.1 (4.6, 5.5)    |4.6 (4.0, 5.2)    |4.9 (4.4, 5.3)    |4.4 (3.7, 5.2)    |2.6 (2.2, 2.9)    |\n\n\n:::\n:::\n\n\nNeither product moves the attack rate among the unimmunized members of its own group by more than the intervals allow, because neither infants nor older adults drive transmission: the infection-blocking component `eff.inf` removes few transmission chains. With 10 simulations the intervals rule out large indirect effects but not small ones, which is the honest statement of this result; compartmental RSV models produce the same qualitative finding, and it is why the products are usually evaluated on direct protection alone. The NPI lowers both rows because it acts on the children who feed infections into every other group.\n\nThe household cocoon is the mirror image: no infant is immunized, so its whole infant effect is indirect, obtained by blocking the household ties through which infants are infected. The per-layer infection counts show why that effect is limited even at complete coverage:\n\n\n::: {#tbl-hh-share .cell}\n\n```{.r .cell-code}\nknitr::kable(t(sapply(res, function(r) round(100 * r$hh_share_infant, 1))),\n             caption = \"Share of infant infections acquired from household contacts (%), by scenario\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Share of infant infections acquired from household contacts (%), by scenario\n\n| none| elderly_vax| infant_proph| both| cocoon| cocoon_random|  npi|\n|----:|-----------:|------------:|----:|------:|-------------:|----:|\n| 41.4|        46.3|         43.2| 44.8|   32.2|          43.4| 47.6|\n\n\n:::\n:::\n\n\nAbout 40% of infant infections come from the household, and the cocoon acts only on that share, through a leaky 50% reduction in the co-residents' own per-contact susceptibility, which protects them by less than 50% over a season of repeated exposure. The remaining exposure is in the community layer, where infants have few contacts but full susceptibility. Every cocooning dose also goes to someone whose own hospitalization risk is low, so the NNI is far worse than the direct product's. The same ordering, direct product over cocooning for severe infant outcomes, appears in household-structured RSV models built for policy.\n\n### Who infects whom\n\nEvery transmission in every simulation was recorded with `set_transmat()`, and `get_transmat()` returns one table per simulation with the extra columns the module added. Pooled over the baseline simulations, the records give the age-by-age transmission matrix, the layer split, and an estimate of the reproduction number: the mean number of secondary infections generated by the seed infections, which were placed at random across ages into a fully susceptible population.\n\n\n::: {#tbl-waifw .cell}\n\n```{.r .cell-code}\ntm_none <- do.call(rbind, lapply(seq_len(nsims), function(s) {\n  as.data.frame(get_transmat(sims$none, sim = s))\n}))\ntm_none$infAge <- factor(tm_none$infAge, levels = age_groups)\ntm_none$susAge <- factor(tm_none$susAge, levels = age_groups)\nwaifw <- round(100 * prop.table(table(infector = tm_none$infAge,\n                                      recipient = tm_none$susAge)), 1)\nknitr::kable(waifw,\n             caption = \"Who infects whom: percent of all baseline infections by infector age group (rows) and recipient age group (columns), pooled over simulations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Who infects whom: percent of all baseline infections by infector age group (rows) and recipient age group (columns), pooled over simulations\n\n|        | infant| young| school| adult| elderly|\n|:-------|------:|-----:|------:|-----:|-------:|\n|infant  |    0.6|   1.0|    0.6|   1.6|     0.1|\n|young   |    2.3|  13.9|    3.0|   8.7|     1.1|\n|school  |    0.6|   2.2|   22.2|  11.9|     1.4|\n|adult   |    0.8|   3.4|    6.6|  12.6|     1.9|\n|elderly |    0.1|   0.3|    0.3|   0.9|     2.0|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaused <- round(100 * prop.table(table(tm_none$infAge)), 1)\nhh_layer <- round(100 * mean(tm_none$layer == 1), 1)\nn_seeds <- round(0.01 * N)\nr_seed <- round(sum(tm_none$infTime == 1) / (n_seeds * nsims), 2)\nc(share_household_layer = hh_layer, secondary_infections_per_seed = r_seed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        share_household_layer secondary_infections_per_seed \n                        44.70                          1.17 \n```\n\n\n:::\n:::\n\n\nSchool-age children cause 38.3% of infections and young children 29%, against 23% of the population between them, and 44.7% of all transmission happens inside households. The seed infections each generated 1.17 secondary infections on average. That number is a reproduction number for a randomly placed infector in a fully susceptible population at the seasonal peak, and it is only modestly above one: the epidemic grows because children, who are contacted and infected more than the average seed, sustain it, and it ends as the seasonal forcing brings transmissibility down and the susceptible children are depleted.\n\n\n::: {#tbl-infant-src .cell}\n\n```{.r .cell-code}\ninf_tm <- tm_none[tm_none$susAge == \"infant\", ]\ninfant_src <- round(100 * prop.table(table(\n  infector = inf_tm$infAge,\n  layer = factor(inf_tm$layer, levels = 1:2, labels = c(\"household\", \"community\")))), 1)\nknitr::kable(infant_src,\n             caption = \"Infant infections by infector age group and layer, percent of all infant infections in the baseline simulations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Infant infections by infector age group and layer, percent of all infant infections in the baseline simulations\n\n|        | household| community|\n|:-------|---------:|---------:|\n|infant  |       0.0|      14.1|\n|young   |      23.9|      29.8|\n|school  |       8.3|       4.7|\n|adult   |       8.9|       9.0|\n|elderly |       0.3|       1.1|\n\n\n:::\n:::\n\n\nThis table is the model's answer to the pathway question. In a rural Kenyan household cohort, 54% of infant infections were acquired within the household and school-age siblings were the index case for most of those ([Munywoki et al. 2014](https://doi.org/10.1093/infdis/jit828)); that setting has larger households and less child care than the one modeled here, and the split is not universal. In this model the household share of infant infections is 41% and the largest single source is young children, at home and in child care. Changing the household mix or the infant entries of the contact profile moves this table directly, which is the point of having it.\n\n### Between-simulation variability\n\n\n::: {#tbl-range .cell}\n\n```{.r .cell-code}\nhosp_total_sims <- do.call(cbind, lapply(res, function(r) per100k(r, age_groups)))\nknitr::kable(round(rbind(mean = colMeans(hosp_total_sims),\n                         min = apply(hosp_total_sims, 2, min),\n                         max = apply(hosp_total_sims, 2, max))),\n             caption = \"All-ages hospitalizations per 100,000: mean and range across simulations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: All-ages hospitalizations per 100,000: mean and range across simulations\n\n|     | none| elderly_vax| infant_proph| both| cocoon| cocoon_random| npi|\n|:----|----:|-----------:|------------:|----:|------:|-------------:|---:|\n|mean |  110|          86|           97|   78|     97|            95|  53|\n|min  |   92|          70|           79|   65|     75|            68|  38|\n|max  |  124|         100|          116|   89|    115|           116|  62|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_none <- as.data.frame(sims$none)\nlast_none <- df_none[df_none$time == max(df_none$time), ]\ncv <- sapply(age_groups, function(a) {\n  v <- last_none[[paste0(\"cuminf.\", a)]]; sd(v) / mean(v)\n})\nround(cv, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n infant   young  school   adult elderly \n   0.09    0.09    0.14    0.10    0.14 \n```\n\n\n:::\n:::\n\n\nA stochastic epidemic that grows only modestly on a clustered network has a wide final-size distribution even with seasonal forcing, and the small strata at the age extremes add sampling noise on top. The coefficient of variation of season-end infections across the 10 baseline simulations is about 0.1 in every age group, so the standard error of a scenario mean is a few percent of its value. That is small next to the 40% reductions the products produce in their own groups and large next to the few-percent movements in untargeted groups, which is why averted hospitalizations are computed within target groups above and why every effect carries an interval. It is also why the example uses `N = 10000` rather than the Gallery's usual 500 to 1500. More simulations narrow the intervals in proportion to the square root of their number; `nsims = 5` halves the run time at the cost of intervals about 40% wider.\n\n## Next Steps\n\n- **Births, infant age in months, and maternal vaccination.** Add an arrivals module so infants are born during the season and receive the antibody at birth or at a catch-up visit, and track infant age in months so that maternal antibody, which protects the youngest infants, can be represented. New arrivals must also be wired into an existing household by appending their edges to `hh.pairs`, which is the one piece of bookkeeping the static layer needs. See [SI with Vital Dynamics](../si-vital-dynamics/) for the aging and arrivals pattern.\n- **Contact persistence.** Raise `duration` in `dissolution_coefs()` for the community layer while holding the profile fixed, so that the same mean degree is made of repeated rather than fresh contacts, and compare the transmission matrix and the household share of infant infections with the daily-replacement version here.\n- **Age-dependent natural history.** Give infants a longer and adults a shorter infectious period, and let the asymptomatic fraction rise with age, as household studies of RSV report.\n- **Weighted household ties.** Give parent-infant, sibling-infant, and grandparent-infant pairs different per-contact probabilities, so that household composition rather than only household size shapes who infects infants.\n- **Waning and multiple seasons.** Add R-to-S waning of natural immunity and a decline in product protection between seasons. The older-adult vaccines lose an estimated 20-30% of their effectiveness per year, which changes the second-season NNI substantially.\n- **Seasonality from data.** The cosine forcing here has an illustrative amplitude and starts the run at the peak. Estimate the amplitude and phase from a surveillance time series, or replace the cosine with the school-calendar forcing that RSV transmission models use, and start the run at season onset with a smaller seed.\n- **Calibration to surveillance data.** Fit the transmission probabilities and `sus.mult` so that the age-specific hospitalization rates match a season of RSV-NET (issue [#58](https://github.com/EpiModel/EpiModel-Gallery/issues/58)).\n- **Exposure-history immunity.** Track the number of prior infections per node instead of using age as the proxy, following the structure in Pitzer et al. (2015).\n- **Cross-layer dependency.** The community layer is independent of household membership. See the [SISMID Multi-Layer Networks tutorial](https://epimodel.github.io/sismid/11_advanced/mod11-Tutorial.html) for a `dat.updates` callback that links degree across layers.\n\n## References\n\nCDC guidance and surveillance (accessed September 2026):\n\n- CDC, RSV vaccine guidance for adults: <https://www.cdc.gov/rsv/hcp/vaccine-clinical-guidance/adults.html>\n- CDC, RSV immunization guidance for infants and young children: <https://www.cdc.gov/rsv/hcp/vaccine-clinical-guidance/infants-young-children.html>\n- CDC, RSV Hospitalization Surveillance Network (RSV-NET): <https://www.cdc.gov/rsv/php/surveillance/rsv-net.html>\n\nProduct trials:\n\n- Hammitt LL, Dagan R, Yuan Y, et al. (2022). Nirsevimab for prevention of RSV in healthy late-preterm and term infants. *N Engl J Med* 386(9):837-846. <https://doi.org/10.1056/NEJMoa2110275>\n- Simões EAF, Madhi SA, Muller WJ, et al. (2023). Efficacy of nirsevimab against respiratory syncytial virus lower respiratory tract infections in preterm and term infants: a pooled analysis of randomised controlled trials. *Lancet Child Adolesc Health* 7(3):180-189. <https://doi.org/10.1016/S2352-4642(22)00321-2>\n- Papi A, Ison MG, Langley JM, et al. (2023). Respiratory syncytial virus prefusion F protein vaccine in older adults. *N Engl J Med* 388(7):595-608. <https://doi.org/10.1056/NEJMoa2209604>\n- Walsh EE, Pérez Marc G, Zareba AM, et al. (2023). Efficacy and safety of a bivalent RSV prefusion F vaccine in older adults. *N Engl J Med* 388(16):1465-1477. <https://doi.org/10.1056/NEJMoa2213836>\n\nEpidemiology, natural history, and contact structure:\n\n- Glezen WP, Taber LH, Frank AL, Kasel JA. (1986). Risk of primary infection and reinfection with respiratory syncytial virus. *Am J Dis Child* 140(6):543-546. <https://doi.org/10.1001/archpedi.1986.02140200053026>\n- Hall CB, Douglas RG, Geiman JM. (1976). Respiratory syncytial virus infections in infants: quantitation and duration of shedding. *J Pediatr* 89(1):11-15. <https://doi.org/10.1016/s0022-3476(76)80918-3>\n- Hall CB, Long CE, Schnabel KC. (2001). Respiratory syncytial virus infections in previously healthy working adults. *Clin Infect Dis* 33(6):792-796. <https://doi.org/10.1086/322657>\n- Falsey AR, Hennessey PA, Formica MA, Cox C, Walsh EE. (2005). Respiratory syncytial virus infection in elderly and high-risk adults. *N Engl J Med* 352(17):1749-1759. <https://doi.org/10.1056/NEJMoa043951>\n- Hall CB, Weinberg GA, Iwane MK, et al. (2009). The burden of respiratory syncytial virus infection in young children. *N Engl J Med* 360(6):588-598. <https://doi.org/10.1056/NEJMoa0804877>\n- Lessler J, Reich NG, Brookmeyer R, Perl TM, Nelson KE, Cummings DAT. (2009). Incubation periods of acute respiratory viral infections: a systematic review. *Lancet Infect Dis* 9(5):291-300. <https://doi.org/10.1016/S1473-3099(09)70069-6>\n- Munywoki PK, Koech DC, Agoti CN, et al. (2014). The source of respiratory syncytial virus infection in infants: a household cohort study in rural Kenya. *J Infect Dis* 209(11):1685-1692. <https://doi.org/10.1093/infdis/jit828>\n- Pitzer VE, Viboud C, Alonso WJ, et al. (2015). Environmental drivers of the spatiotemporal dynamics of respiratory syncytial virus in the United States. *PLoS Pathog* 11(1):e1004591. <https://doi.org/10.1371/journal.ppat.1004591>\n- Mossong J, Hens N, Jit M, et al. (2008). Social contacts and mixing patterns relevant to the spread of infectious diseases. *PLoS Med* 5(3):e74. <https://doi.org/10.1371/journal.pmed.0050074>\n\nRSV scenario modeling tools:\n\n- RSV Scenario Modeling Hub: <https://rsvscenariomodelinghub.org/> (Round 4 scenario definitions and intervention effectiveness, accessed September 2026: <https://github.com/midas-network/rsv-scenario-modeling-hub>)\n- Hansen CL, et al. R.Scenario.Vax: scenario projections of RSV hospitalizations from RSV-NET data. <https://chelsea-hansen.github.io/R.Scenario.Vax/>\n- Hansen CL, et al. (2025). Scenario projections of respiratory syncytial virus hospitalizations averted due to new immunizations. *JAMA Netw Open* 8(6):e2514622. <https://doi.org/10.1001/jamanetworkopen.2025.14622>\n\nThe household mix, community contact profile, per-contact transmission probabilities, susceptibility multipliers, and per-infection hospitalization risks are illustrative choices selected to reproduce the qualitative RSV pattern (attack rates decreasing with age after early childhood, hospitalization burden at the age extremes, children as the transmission amplifier). They are not calibrated to any surveillance dataset or season.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}